export const DOMAINS = [
  'Agriculture Mechanization',
  'Agricultural Schemes & Subsidies',
  'Bio-Pesticides and Bio-Fertilizers',
  'Crop Insurance',
  'Cultural Practices',
  'Cultural and Crop Management Practices',
  'Climate, Weather & Stress Management',
  'Credit, Loan & Insurance',
  'Disease Management',
  'Fertilizer Use and Availability',
  'Field Preparation',
  'Farm Tools & Mechanisation',
  'Irrigation and Water Management',
  'Insect–Pest Management',
  'Market Prices, MSP & Marketing',
  'Nutrient Management',
  'Organic Farming',
  'Organic and Natural Farming',
  'Plant Protection',
  'Post Harvest Preservation',
  'Post-Harvest Management & Storage',
  'Seeds',
  'Seed and Variety Selection',
  'Soil Health Card',
  'Soil Testing',
  'Soil Health and Nutrient Management',
  'Sowing Time and Weather',
  'Storage',
  'Varieties',
  'Water Management',
  'Weed Management',
  'Market Information',
  'Others',
] as const;

export type Domain = (typeof DOMAINS)[number];