// Crop image lookup: maps crop name -> bundled SVG asset filename.
// Image files live in web/assets/Crops/<name>.svg (served at /Crops/<name>.svg
// via vite's publicDir) and are named after the crop, matching the mobile app's
// convention. `/` is not a valid filename character, so a crop name containing
// one (e.g. "Bajra/Pearl millet") maps to a file with the slash replaced by a
// space (e.g. "Bajra Pearl millet.svg") -- see the value below for the exact name.

const _map: Record<string, string> = {
  "Adapathiyan": "Adapathiyan",
  "Agathi /sesbania grandiflora": "Agathi sesbania grandiflora",
  "Ailanthus or Matti": "Ailanthus or Matti",
  "Ajwain (Carom seeds)": "Ajwain (Carom seeds)",
  "Allspice": "Allspice",
  "Almond": "Almond",
  "Aloe vera": "Aloe vera",
  "Amaranthus": "Amaranthus",
  "Anthurium": "Anthurium",
  "Apple": "Apple",
  "Apricot": "Apricot",
  "Arecanut": "Arecanut",
  "Arhar Dal (Red Gram)": "Arhar Dal (Red Gram)",
  "Aromatic Rice": "Aromatic Rice",
  "Arrow root": "Arrow root",
  "Arum (Elephant Foot Yam)": "Arum (Elephant Foot Yam)",
  "Arum Stem": "Arum Stem",
  "Ash Gourd": "Ash Gourd",
  "Ashwagandha": "Ashwagandha",
  "Asoka": "Asoka",
  "Avocado": "Avocado",
  "Babool / Indian gum arabic tree": "Babool Indian gum arabic tree",
  "Baby corn": "Baby corn",
  "Bajra/Pearl millet": "Bajra Pearl millet",
  "Bamboo": "Bamboo",
  "Banana": "Banana",
  "Banana Stem": "Banana Stem",
  "Barley": "Barley",
  "Barnyard Millet": "Barnyard Millet",
  "Beans": "Beans",
  "Beet root": "Beet root",
  "Bengal Gram/Chickpea": "Bengal Gram Chickpea",
  "Berseem": "Berseem",
  "Betel Leaf": "Betel Leaf",
  "Betel vine": "Betel vine",
  "Bethua Leaves": "Bethua Leaves",
  "Bird of paradise": "Bird of paradise",
  "Bitter Gourd": "Bitter Gourd",
  "Black Cumin": "Black Cumin",
  "Black Gram": "Black Gram",
  "Black Grapes": "Black Grapes",
  "Black Pepper": "Black Pepper",
  "Blueberry": "Blueberry",
  "Bottle Gourd": "Bottle Gourd",
  "Brahmi": "Brahmi",
  "Brinjal (Eggplant)": "Brinjal (Eggplant)",
  "Broad beans": "Broad beans",
  "Broccoli": "Broccoli",
  "Brown Top Millet": "Brown Top Millet",
  "Buckwheat": "Buckwheat",
  "Butter / Mahua Tree": "Butter Mahua Tree",
  "Cabbage": "Cabbage",
  "Camboge": "Camboge",
  "Capsicum": "Capsicum",
  "Cardamom": "Cardamom",
  "Carnation": "Carnation",
  "Carom": "Carom",
  "Carrot": "Carrot",
  "Cashew": "Cashew",
  "Cassava (Tapioca)": "Cassava (Tapioca)",
  "Cassia": "Cassia",
  "Castor": "Castor",
  "Casuarina": "Casuarina",
  "Cauliflower": "Cauliflower",
  "Celery": "Celery",
  "Celery Seeds": "Celery Seeds",
  "Ceylon Spinach": "Ceylon Spinach",
  "Chadachi": "Chadachi",
  "Chayote": "Chayote",
  "Chengazhinirkizhangu": "Chengazhinirkizhangu",
  "Chethikoduveli": "Chethikoduveli",
  "Chikoo / sapodilla": "Chikoo sapodilla",
  "Chilli": "Chilli",
  "China aster": "China aster",
  "Chinese cabbage": "Chinese cabbage",
  "Chittadalotakam": "Chittadalotakam",
  "Chittaratha": "Chittaratha",
  "Chrysanthemum": "Chrysanthemum",
  "Cinnamon": "Cinnamon",
  "Citronella grass": "Citronella grass",
  "Citrus": "Citrus",
  "Clove": "Clove",
  "Cluster bean": "Cluster bean",
  "Cocoa": "Cocoa",
  "Coconut": "Coconut",
  "Coffee": "Coffee",
  "Coleus": "Coleus",
  "Colocasia": "Colocasia",
  "Congosignal grass": "Congosignal grass",
  "Coriander (Cilantro)": "Coriander (Cilantro)",
  "Coriander Leaves/Seeds": "Coriander Leaves Seeds",
  "Cotton": "Cotton",
  "Cowpea": "Cowpea",
  "Crossandra": "Crossandra",
  "Cucumber": "Cucumber",
  "Cumin Seeds": "Cumin Seeds",
  "Curry leaves": "Curry leaves",
  "Custard Apple": "Custard Apple",
  "Daincha": "Daincha",
  "Danthappala": "Danthappala",
  "Darjeeling Orange": "Darjeeling Orange",
  "Date": "Date",
  "Date Palm": "Date Palm",
  "Davana": "Davana",
  "Dill leaves": "Dill leaves",
  "Dragon Fruit": "Dragon Fruit",
  "Drumstick (Moringa)": "Drumstick (Moringa)",
  "Elephant Apple": "Elephant Apple",
  "Eucalyptus": "Eucalyptus",
  "Fennel": "Fennel",
  "Fenugreek (Methi)": "Fenugreek (Methi)",
  "Field pea": "Field pea",
  "Fig": "Fig",
  "Finger Millet /ragi": "Finger Millet ragi",
  "Fodder cowpea": "Fodder cowpea",
  "Fodder maize": "Fodder maize",
  "Fodder sorghum": "Fodder sorghum",
  "Foxtail Millet": "Foxtail Millet",
  "French bean": "French bean",
  "Gaillardia": "Gaillardia",
  "Galgal (Hill Lemon)": "Galgal (Hill Lemon)",
  "Gamba grass": "Gamba grass",
  "Garlic": "Garlic",
  "Geranium": "Geranium",
  "Gerbera": "Gerbera",
  "German Turnip": "German Turnip",
  "Gherkins": "Gherkins",
  "Ginger": "Ginger",
  "Gladiolus": "Gladiolus",
  "Gliricidia": "Gliricidia",
  "Grape": "Grape",
  "Greater yam": "Greater yam",
  "Green Cardamom": "Green Cardamom",
  "Green Chilli": "Green Chilli",
  "Green Gram": "Green Gram",
  "Green Mango": "Green Mango",
  "Green Papaya": "Green Papaya",
  "Green Peas": "Green Peas",
  "Ground Nut": "Ground Nut",
  "Guava": "Guava",
  "Guinea grass": "Guinea grass",
  "Gymnema (Sugar destroyer)": "Gymnema (Sugar destroyer)",
  "Hedge lucerne": "Hedge lucerne",
  "Heliconia": "Heliconia",
  "Hogplum": "Hogplum",
  "Holy basil": "Holy basil",
  "Hops": "Hops",
  "Horse Gram": "Horse Gram",
  "Hyacinth Bean or Lablab Bean": "Hyacinth Bean or Lablab Bean",
  "Hybrid napier": "Hybrid napier",
  "Indian Beech / Pongam Tree": "Indian Beech Pongam Tree",
  "Indian Blackberry": "Indian Blackberry",
  "Indian Gooseberry (Amla)": "Indian Gooseberry (Amla)",
  "Indian Jujube (Ber)": "Indian Jujube (Ber)",
  "Indian hogweed / Spiny amaranth": "Indian hogweed Spiny amaranth",
  "Indian mustard": "Indian mustard",
  "Indian sarsaparilla (Mangani root)": "Indian sarsaparilla (Mangani root)",
  "Indigo / neela amari": "Indigo neela amari",
  "Irul": "Irul",
  "Ivy Gourd": "Ivy Gourd",
  "Jack Fruit": "Jack Fruit",
  "Jamun fruit": "Jamun fruit",
  "Japanese Persimmon": "Japanese Persimmon",
  "Jasmine": "Jasmine",
  "Jeevakam /crepidiam": "Jeevakam crepidiam",
  "Jicama": "Jicama",
  "Jute Leaves": "Jute Leaves",
  "Kachhuram": "Kachhuram",
  "Kagzi Lime": "Kagzi Lime",
  "Kampakam/hopea parviflora": "Kampakam hopea parviflora",
  "Kanjiram /nux vomica": "Kanjiram nux vomica",
  "Karinochi /vitex negundo": "Karinochi vitex negundo",
  "Karonda / carissa": "Karonda carissa",
  "Kashi kanagile /periwinkle": "Kashi kanagile periwinkle",
  "Kasthurimanjal /wild turmeric": "Kasthurimanjal wild turmeric",
  "Kidney bean/Rajama": "Kidney bean Rajama",
  "Kinnow (mandarin)": "Kinnow (mandarin)",
  "Kiwifruit": "Kiwifruit",
  "Knol-khol": "Knol-khol",
  "Kodo millet": "Kodo millet",
  "Kokum": "Kokum",
  "Koovalam": "Koovalam",
  "Kurumthotti / country mallow": "Kurumthotti country mallow",
  "Kusuma /safflower": "Kusuma safflower",
  "Lady's Finger / okra": "Lady's Finger okra",
  "Large Cardamom": "Large Cardamom",
  "Lemongrass": "Lemongrass",
  "Lentil": "Lentil",
  "Lesser yarm": "Lesser yarm",
  "Lettuce": "Lettuce",
  "Lime / Lemon": "Lime Lemon",
  "Linseed, Flax": "Linseed, Flax",
  "Litchi": "Litchi",
  "Little Millet": "Little Millet",
  "Long melon": "Long melon",
  "Long pepper": "Long pepper",
  "Loquat": "Loquat",
  "Lucerne": "Lucerne",
  "Mahagony": "Mahagony",
  "Maize": "Maize",
  "Malabar Neem": "Malabar Neem",
  "Mandarin orange": "Mandarin orange",
  "Mangium": "Mangium",
  "Mango": "Mango",
  "Mango-ginger": "Mango-ginger",
  "Mangosteen": "Mangosteen",
  "Marigold": "Marigold",
  "Matar Dal (Split peas)": "Matar Dal (Split peas)",
  "Mentha": "Mentha",
  "Mesta / roselle": "Mesta roselle",
  "Moth Bean": "Moth Bean",
  "Mushroom": "Mushroom",
  "Muskmelon": "Muskmelon",
  "Mustard": "Mustard",
  "Musur Dal": "Musur Dal",
  "Napier Grass": "Napier Grass",
  "Niger": "Niger",
  "Nilappana / ground plam": "Nilappana ground plam",
  "Nutmeg": "Nutmeg",
  "Oats": "Oats",
  "Oilpalm": "Oilpalm",
  "Olive": "Olive",
  "Onion": "Onion",
  "Orange (Sweet Orange / Mosambi)": "Orange (Sweet Orange Mosambi)",
  "Orchids": "Orchids",
  "Paddy": "Paddy",
  "Palmarosa grass": "Palmarosa grass",
  "Palmyra palm": "Palmyra palm",
  "Papaya": "Papaya",
  "Para grass": "Para grass",
  "Paradise Tree": "Paradise Tree",
  "Passion fruit": "Passion fruit",
  "Patchouli": "Patchouli",
  "Pathimugham / sappan wood": "Pathimugham sappan wood",
  "Pea": "Pea",
  "Peach": "Peach",
  "Pear": "Pear",
  "Pecan Nut": "Pecan Nut",
  "Physic Nut / Jatropha": "Physic Nut Jatropha",
  "Pickling melon": "Pickling melon",
  "Pineapple": "Pineapple",
  "Plum": "Plum",
  "Pointed Gourd": "Pointed Gourd",
  "Pomegranate": "Pomegranate",
  "Potato": "Potato",
  "Proso millet": "Proso millet",
  "Pumpkin": "Pumpkin",
  "Punna": "Punna",
  "Quina": "Quina",
  "Raddish": "Raddish",
  "Ramboothan": "Ramboothan",
  "Ramphal": "Ramphal",
  "Red Chilli": "Red Chilli",
  "Red Gram/Pigeon Pea": "Red Gram Pigeon Pea",
  "Red Sanders / Red Sandalwood": "Red Sanders Red Sandalwood",
  "Rice": "Rice",
  "Ridge Gourd": "Ridge Gourd",
  "Rose": "Rose",
  "Rosemary": "Rosemary",
  "Rosewood": "Rosewood",
  "Round gourd": "Round gourd",
  "Rubber": "Rubber",
  "Ryegrass": "Ryegrass",
  "Safed musli": "Safed musli",
  "Sarpagandha (Indian snakeroot)": "Sarpagandha (Indian snakeroot)",
  "Senji / indian sweet clover": "Senji indian sweet clover",
  "Sesame, Gingelly": "Sesame, Gingelly",
  "Setaria grass": "Setaria grass",
  "Shaftal": "Shaftal",
  "Snake Gourd": "Snake Gourd",
  "Sorghum": "Sorghum",
  "Sorghum (Fodder)": "Sorghum (Fodder)",
  "Soyabean": "Soyabean",
  "Spinach": "Spinach",
  "Sponge gourd": "Sponge gourd",
  "Squash": "Squash",
  "Stevia": "Stevia",
  "Strawberry": "Strawberry",
  "Stylo": "Stylo",
  "Subabul": "Subabul",
  "Sugarbeet": "Sugarbeet",
  "Sugarcane": "Sugarcane",
  "Sun hemp": "Sun hemp",
  "Sunflower": "Sunflower",
  "Sweet Cherry": "Sweet Cherry",
  "Sweet Lemon": "Sweet Lemon",
  "Sweet Lime": "Sweet Lime",
  "Sweet orange": "Sweet orange",
  "Sweet pepper": "Sweet pepper",
  "Sweet potato": "Sweet potato",
  "Tamarind": "Tamarind",
  "Tea": "Tea",
  "Teak": "Teak",
  "Thembavu": "Thembavu",
  "Thorny bamboo": "Thorny bamboo",
  "Tobacco": "Tobacco",
  "Tomato": "Tomato",
  "Tree Tomato": "Tree Tomato",
  "Tuberose": "Tuberose",
  "Turmeric": "Turmeric",
  "Turnip": "Turnip",
  "Vanilla": "Vanilla",
  "Vegetable cowpea": "Vegetable cowpea",
  "Venga": "Venga",
  "Vetiver (Khus grass)": "Vetiver (Khus grass)",
  "Walnut": "Walnut",
  "Water melon": "Water melon",
  "West Indian Cherry": "West Indian Cherry",
  "Wheat": "Wheat",
  "White yam": "White yam",
  "Wild Tamarind": "Wild Tamarind",
  "Wild date palm": "Wild date palm",
  "Wild indigo": "Wild indigo",
  "Wild jack or Aini": "Wild jack or Aini",
  "Wood apple": "Wood apple",
}

// `CROPS` (constants/public.ts) is a much larger, messier list -- 400+ short
// forms, regional names and near-duplicates mirrored from the mobile app's
// registration form (e.g. "Linseed", "Moong", "Amla", "Urd") -- that don't
// exact/normalise-match any of the 315 canonical crop names above (e.g.
// "Linseed" vs. "Linseed, Flax", "Amla" vs. "Indian Gooseberry (Amla)").
// Hand-mapped here to the correct canonical image; anything genuinely
// ambiguous (e.g. bare "Millet", "Gram", "Yam") is deliberately left out --
// falling back to the placeholder icon beats guessing wrong.
const _ALIASES: Record<string, string> = {
  Agathi: "Agathi sesbania grandiflora",
  Amaranth: "Amaranthus",
  Amla: "Indian Gooseberry (Amla)",
  Arhar: "Arhar Dal (Red Gram)",
  "Arum Lobe": "Arum (Elephant Foot Yam)",
  "Babool Tree": "Babool Indian gum arabic tree",
  Babycorn: "Baby corn",
  Beetroot: "Beet root",
  "Bengal Gram": "Bengal Gram Chickpea",
  Ber: "Indian Jujube (Ber)",
  "Ber (Jujube)": "Indian Jujube (Ber)",
  Brinjal: "Brinjal (Eggplant)",
  Brocolli: "Broccoli",
  "Chick pea": "Bengal Gram Chickpea",
  Chickpea: "Bengal Gram Chickpea",
  "Chickpea, Bengal gram": "Bengal Gram Chickpea",
  Chikoo: "Chikoo sapodilla",
  Chilly: "Chilli",
  "Chow Chow": "Chayote",
  Cloves: "Clove",
  Colocacia: "Colocasia",
  Coriander: "Coriander (Cilantro)",
  Cumin: "Cumin Seeds",
  Dillseed: "Dill leaves",
  Drumstick: "Drumstick (Moringa)",
  "Elephant Foot Yam": "Arum (Elephant Foot Yam)",
  Fenugreek: "Fenugreek (Methi)",
  "Finger Millet": "Finger Millet ragi",
  "Finger millet": "Finger Millet ragi",
  "Firecracker flower": "Crossandra",
  Grapes: "Grape",
  "Green gram, Golden gram": "Green Gram",
  "Green pea": "Green Peas",
  "Greeng gram": "Green Gram",
  Groundnut: "Ground Nut",
  Horsegram: "Horse Gram",
  "Hyacinth Bean": "Hyacinth Bean or Lablab Bean",
  "Indian Beech Tree": "Indian Beech Pongam Tree",
  "Indian Butter Tree / Mahua": "Butter Mahua Tree",
  "Indian Gooseberry": "Indian Gooseberry (Amla)",
  "Indian gooseberry": "Indian Gooseberry (Amla)",
  Indigo: "Indigo neela amari",
  Jack: "Jack Fruit",
  Jackfruit: "Jack Fruit",
  Jamun: "Jamun fruit",
  Jeevakom: "Jeevakam crepidiam",
  Kacholam: "Kachhuram",
  "Kalai Dal": "Black Gram",
  Kampakam: "Kampakam hopea parviflora",
  Kanjiram: "Kanjiram nux vomica",
  Karinochi: "Karinochi vitex negundo",
  Karonda: "Karonda carissa",
  "Kashi kanagile": "Kashi kanagile periwinkle",
  Kasthurimanjal: "Kasthurimanjal wild turmeric",
  Kattarvazha: "Aloe vera",
  "Kidney Bean": "Kidney bean Rajama",
  "Kidney bean": "Kidney bean Rajama",
  Kurumthotti: "Kurumthotti country mallow",
  Kusuma: "Kusuma safflower",
  "Lady's Finger": "Lady's Finger okra",
  Lemon: "Lime Lemon",
  Linseed: "Linseed, Flax",
  Mahogany: "Mahagony",
  Mandarin: "Mandarin orange",
  Mash: "Black Gram",
  Mesta: "Mesta roselle",
  Moong: "Green Gram",
  "Moong Dal": "Green Gram",
  Mung: "Green Gram",
  "Mung bean": "Green Gram",
  "Neela amari": "Indigo neela amari",
  Nilappana: "Nilappana ground plam",
  Oat: "Oats",
  Okra: "Lady's Finger okra",
  "Okra (Lady’s finger)": "Lady's Finger okra",
  Orange: "Orange (Sweet Orange Mosambi)",
  "Paddy/Rice": "Paddy",
  Palmarosa: "Palmarosa grass",
  Pathimugham: "Pathimugham sappan wood",
  "Pearl Millet": "Bajra Pearl millet",
  "Pearl millet": "Bajra Pearl millet",
  "Pigeon Pea": "Red Gram Pigeon Pea",
  "Pigeon pea": "Red Gram Pigeon Pea",
  "Pigeon pea, Red gram": "Red Gram Pigeon Pea",
  "Proso milllet": "Proso millet",
  Radish: "Raddish",
  Ragi: "Finger Millet ragi",
  "Rapeseed and Mustard": "Mustard",
  "Raw Bengal Gram": "Bengal Gram Chickpea",
  "Red gram": "Red Gram Pigeon Pea",
  "Rice (Paddy)": "Rice",
  "Ripe Papaya": "Papaya",
  "Rose (Greenhouse)": "Rose",
  "Roselle / Red sorrel": "Mesta roselle",
  Safflower: "Kusuma safflower",
  "Sapodilla (Chiku)": "Chikoo sapodilla",
  Sapota: "Chikoo sapodilla",
  Senji: "Senji indian sweet clover",
  Sesame: "Sesame, Gingelly",
  "Shah Marich": "Long pepper",
  Shevri: "Agathi sesbania grandiflora",
  "Sorghum (Rabi/Kharif)": "Sorghum",
  Soybean: "Soyabean",
  "Summer squash": "Squash",
  Tapioca: "Cassava (Tapioca)",
  Thippali: "Long pepper",
  Thulasi: "Holy basil",
  "Tulsi (Holy basil)": "Holy basil",
  Urd: "Black Gram",
  Vetiver: "Vetiver (Khus grass)",
  Wanga: "Brinjal (Eggplant)",
  Watermelon: "Water melon",
}

const _all: Record<string, string> = { ..._map, ..._ALIASES }

// Pre-compute a lowercase lookup once for fast matching.
const _lower: Record<string, string> = {}
for (const k of Object.keys(_all)) {
  _lower[k.toLowerCase()] = _all[k]
}

// Normalise a crop name for matching:
//   - lower-case
//   - treat '(' ')' '/' as word separators
//   - collapse whitespace
function normalise(name: string): string {
  return name.toLowerCase().replace(/[()/]/g, " ").replace(/\s+/g, " ").trim()
}

const _normalised: Record<string, string> = {}
for (const k of Object.keys(_all)) {
  _normalised[normalise(k)] = _all[k]
}

/**
 * Returns the public URL for a crop's image, or null if no matching
 * image is bundled. Matching is case-insensitive and tolerant of minor
 * punctuation differences (e.g. "Bajra/Pearl millet" -> "Bajra Pearl millet").
 */
export function getCropImage(cropName: string | null | undefined): string | null {
  if (!cropName) return null
  const file =
    _map[cropName] ??
    _lower[cropName.toLowerCase()] ??
    _normalised[normalise(cropName)]
  if (!file) return null
  return `/Crops/${encodeURIComponent(file)}.svg`
}
