// Crop image lookup: maps crop name → bundled asset.
// To add a new crop image, drop the file into assets/Crops/ and add a matching
// `require('../../assets/Crops/Foo.jpg')` entry below.

import type { ImageSourcePropType } from "react-native";

export type CropImageMap = Record<string, ImageSourcePropType>;

const _map: CropImageMap = {
  Adapathiyan: require("../../assets/Crops/Adapathiyan.jpg"),
  Agathi: require("../../assets/Crops/Agathi.jpeg"),
  "Ailanthus or Matti": require("../../assets/Crops/Ailanthus or Matti.jpeg"),
  "Ajwain (Carom seeds)": require("../../assets/Crops/Ajwain (Carom seeds).jpg"),
  Allspice: require("../../assets/Crops/Allspice.jpg"),
  Almond: require("../../assets/Crops/Almond.jpg"),
  "Aloe vera": require("../../assets/Crops/Aloe vera.jpg"),
  Amaranth: require("../../assets/Crops/Amaranth.jpg"),
  Amaranthus: require("../../assets/Crops/Amaranthus.jpg"),
  Amla: require("../../assets/Crops/Amla.jpg"),
  Anthurium: require("../../assets/Crops/Anthurium.jpg"),
  Apple: require("../../assets/Crops/Apple.jpg"),
  Apricot: require("../../assets/Crops/Apricot.jpg"),
  Arecanut: require("../../assets/Crops/Arecanut.jpeg"),
  "Arhar Dal (Red Gram)": require("../../assets/Crops/Arhar Dal (Red Gram).jpg"),
  Arhar: require("../../assets/Crops/Arhar.jpg"),
  "Aromatic Rice": require("../../assets/Crops/Aromatic Rice.jpeg"),
  "Arrow root": require("../../assets/Crops/Arrow root.jpg"),
  "Arum (Elephant Foot Yam)": require("../../assets/Crops/Arum (Elephant Foot Yam).jpg"),
  "Arum Lobe": require("../../assets/Crops/Arum Lobe.jpg"),
  "Arum Stem": require("../../assets/Crops/Arum Stem.jpg"),
  "Ash gourd": require("../../assets/Crops/Ash gourd.jpeg"),
  "Ash Gourd": require("../../assets/Crops/Ash Gourd.jpg"),
  Ashwagandha: require("../../assets/Crops/Ashwagandha.jpg"),
  Asoka: require("../../assets/Crops/Asoka.jpg"),
  Avocado: require("../../assets/Crops/Avocado.jpeg"),
  "Babool / Indian gum arabic tree": require("../../assets/Crops/Babool Indian gum arabic tree.jpg"),
  "Babool Tree": require("../../assets/Crops/Babool Tree.jpg"),
  "Baby corn": require("../../assets/Crops/Baby corn.jpg"),
  Babycorn: require("../../assets/Crops/Babycorn.jpg"),
  "Bajra/Pearl millet": require("../../assets/Crops/Bajra Pearl millet.jpg"),
  Bamboo: require("../../assets/Crops/Bamboo.jpg"),
  "Banana Stem": require("../../assets/Crops/Banana Stem.jpg"),
  Banana: require("../../assets/Crops/Banana.jpeg"),
  Barley: require("../../assets/Crops/Barley.jpg"),
  "Barnyard Millet": require("../../assets/Crops/Barnyard Millet.png"),
  Beans: require("../../assets/Crops/Beans.png"),
  "Beet root": require("../../assets/Crops/Beet root.png"),
  Beetroot: require("../../assets/Crops/Beetroot.png"),
  "Bengal Gram/Chickpea": require("../../assets/Crops/Bengal Gram Chickpea.png"),
  "Bengal Gram": require("../../assets/Crops/Bengal Gram.png"),
  "Ber (Jujube)": require("../../assets/Crops/Ber (Jujube).jpg"),
  Ber: require("../../assets/Crops/Ber.jpeg"),
  Berseem: require("../../assets/Crops/Berseem.jpg"),
  "Betel Leaf": require("../../assets/Crops/Betel Leaf.jpg"),
  "Betel vine": require("../../assets/Crops/Betel vine.jpg"),
  "Bethua Leaves": require("../../assets/Crops/Bethua Leaves.jpg"),
  "Beto Shak": require("../../assets/Crops/Beto Shak.jpg"),
  "Bird of paradise": require("../../assets/Crops/Bird of paradise.jpg"),
  "Bitter Gourd": require("../../assets/Crops/Bitter Gourd.jpg"),
  "Black Cumin": require("../../assets/Crops/Black Cumin.png"),
  "Black Gram": require("../../assets/Crops/Black gram.jpg"),
  "Black Grapes": require("../../assets/Crops/Black Grapes.jpg"),
  "Black Pepper": require("../../assets/Crops/Black Pepper.jpeg"),
  "Black gram": require("../../assets/Crops/Black gram.jpg"),
  Blueberry: require("../../assets/Crops/Blueberry.jpg"),
  "Borassus flabellifer": require("../../assets/Crops/Borassus flabellifer.jpg"),
  "Bottle Gourd": require("../../assets/Crops/Bottle Gourd.jpeg"),
  Brahmi: require("../../assets/Crops/Brahmi.jpg"),
  "Brassica juncea": require("../../assets/Crops/Brassica juncea.jpg"),
  "Brinjal / Eggplant": require("../../assets/Crops/Brinjal  Eggplant.jpg"),
  "Brinjal (Eggplant)": require("../../assets/Crops/Brinjal (Eggplant).jpg"),
  Brinjal: require("../../assets/Crops/Brinjal.jpg"),
  "Broad beans": require("../../assets/Crops/Broad beans.jpg"),
  Broccoli: require("../../assets/Crops/Broccoli.png"),
  Brocolli: require("../../assets/Crops/Broccoli.png"),
  "Brown Top Millet": require("../../assets/Crops/Brown Top Millet.png"),
  Buckwheat: require("../../assets/Crops/Buckwheat.jpg"),
  "Butter / Mahua Tree": require("../../assets/Crops/Butter Mahua Tree.jpg"),
  Cabbage: require("../../assets/Crops/Cabbage.png"),
  Camboge: require("../../assets/Crops/Camboge.png"),
  Capsicum: require("../../assets/Crops/Capsicum.png"),
  Cardamom: require("../../assets/Crops/Cardamom.png"),
  Carom: require("../../assets/Crops/Ajwain (Carom seeds).jpg"),
  Carnation: require("../../assets/Crops/Carnation.png"),
  Carrot: require("../../assets/Crops/Carrot.png"),
  Cashew: require("../../assets/Crops/Cashew.jpg"),
  "Cassava (Tapioca)": require("../../assets/Crops/Cassava (Tapioca).jpg"),
  Cassia: require("../../assets/Crops/Cassia.png"),
  Castor: require("../../assets/Crops/Castor.jpg"),
  Casuarina: require("../../assets/Crops/Casuarina.jpg"),
  Cauliflower: require("../../assets/Crops/Cauliflower.png"),
  "Celery Seeds": require("../../assets/Crops/Celery Seeds.jpeg"),
  Celery: require("../../assets/Crops/Celery.jpeg"),
  "Ceylon Spinach": require("../../assets/Crops/Ceylon Spinach.jpg"),
  Chadachi: require("../../assets/Crops/Chadachi.jpg"),
  "Char Magaz": require("../../assets/Crops/Char Magaz.png"),
  Chayote: require("../../assets/Crops/Chayote.jpg"),
  Chengazhinirkizhangu: require("../../assets/Crops/Chengazhinirkizhangu.png"),
  Chethikoduveli: require("../../assets/Crops/Chethikoduveli.png"),
  "Chick pea": require("../../assets/Crops/Chick pea.png"),
  "Chickpea, Bengal gram": require("../../assets/Crops/Chickpea Bengal gram.png"),
  Chickpea: require("../../assets/Crops/Chickpea.png"),
  Chikoo: require("../../assets/Crops/Chikoo.jpg"),
  Chilli: require("../../assets/Crops/Chilli.jpg"),
  Chilly: require("../../assets/Crops/Chilly.jpg"),
  "China aster": require("../../assets/Crops/China aster.png"),
  "Chinese cabbage": require("../../assets/Crops/Chinese cabbage.png"),
  Chittadalotakam: require("../../assets/Crops/Chittadalotakam.png"),
  Chittaratha: require("../../assets/Crops/Chittaratha.png"),
  "Chow Chow": require("../../assets/Crops/Chow Chow.jpg"),
  Chrysanthemum: require("../../assets/Crops/Chrysanthemum.jpeg"),
  Cinnamon: require("../../assets/Crops/Cinnamon.jpg"),
  "Citronella grass": require("../../assets/Crops/Citronella grass.jpeg"),
  Citrus: require("../../assets/Crops/Citrus.jpg"),
  clove: require("../../assets/Crops/clove.png"),
  cloves: require("../../assets/Crops/cloves.png"),
  "Cluster bean": require("../../assets/Crops/Cluster bean.png"),
  Cocoa: require("../../assets/Crops/Cocoa.jpg"),
  Coconut: require("../../assets/Crops/Coconut.jpg"),
  Coffee: require("../../assets/Crops/Coffee.jpg"),
  Coleus: require("../../assets/Crops/Coleus.png"),
  Colocacia: require("../../assets/Crops/Colocacia.jpg"),
  Colocasia: require("../../assets/Crops/Colocasia.jpg"),
  "Congosignal grass": require("../../assets/Crops/Congosignal grass.jpg"),
  "Coriander (Cilantro)": require("../../assets/Crops/Coriander (Cilantro).jpg"),
  "Coriander Leaves/Seeds": require("../../assets/Crops/Coriander Leaves Seeds.jpg"),
  Coriander: require("../../assets/Crops/Coriander.jpg"),
  Cotton: require("../../assets/Crops/Cotton.jpeg"),
  Cowpea: require("../../assets/Crops/Cowpea.jpg"),
  Crossandra: require("../../assets/Crops/Crossandra.jpeg"),
  Cucumber: require("../../assets/Crops/Cucumber.png"),
  "Cumin": require("../../assets/Crops/Cumin.jpg"),
  "Cumin Seeds": require("../../assets/Crops/Cumin Seeds.png"),
  "Curculigo orchioides": require("../../assets/Crops/Curculigo orchioides.jpg"),
  "Curcuma amada": require("../../assets/Crops/Curcuma amada.png"),
  "Curry leaves": require("../../assets/Crops/Curry leaves.jpg"),
  "Custard Apple": require("../../assets/Crops/Custard Apple.jpeg"),
  Daincha: require("../../assets/Crops/Daincha.jpg"),
  Danthappala: require("../../assets/Crops/Danthappala.jpeg"),
  "Darjeeling Orange": require("../../assets/Crops/Darjeeling Orange.png"),
  "Date Palm": require("../../assets/Crops/Date Palm.jpeg"),
  Date: require("../../assets/Crops/Date.jpeg"),
  Davana: require("../../assets/Crops/Davana.png"),
  "Dill leaves": require("../../assets/Crops/Dill leaves.jpg"),
  Dillseed: require("../../assets/Crops/Dillseed.png"),
  "Dragon Fruit": require("../../assets/Crops/Dragon Fruit.jpg"),
  Drumstick: require("../../assets/Crops/Drumstick.jpg"),
  "Drumstick (Moringa)": require("../../assets/Crops/Drumstick.jpg"),
  "Elephant Apple": require("../../assets/Crops/Elephant Apple.jpg"),
  "Elephant Foot Yam": require("../../assets/Crops/Elephant Foot Yam.jpg"),
  Eucalyptus: require("../../assets/Crops/Eucalyptus.jpg"),
  Fennel: require("../../assets/Crops/Fennel.jpg"),
  Fenugreek: require("../../assets/Crops/Fenugreek.png"),
  "Fenugreek (Methi)": require("../../assets/Crops/Fenugreek.png"),
  "Field pea": require("../../assets/Crops/Field pea.jpg"),
  Fig: require("../../assets/Crops/Fig.jpg"),
  "Finger Millet": require("../../assets/Crops/Finger Millet.png"),
  "Firecracker flower": require("../../assets/Crops/Firecracker flower.jpg"),
  "Fodder cowpea": require("../../assets/Crops/Fodder cowpea.jpg"),
  "Fodder maize": require("../../assets/Crops/Fodder maize.jpg"),
  "Fodder sorghum": require("../../assets/Crops/Fodder sorghum.jpg"),
  "Foxtail millet": require("../../assets/Crops/Foxtail millet.jpg"),
  "French bean": require("../../assets/Crops/French bean.png"),
  Gaillardia: require("../../assets/Crops/Gaillardia.jpg"),
  "Galgal (Hill Lemon)": require("../../assets/Crops/Galgal (Hill Lemon).png"),
  "Gamba grass": require("../../assets/Crops/Gamba grass.png"),
  Garlic: require("../../assets/Crops/Garlic.jpg"),
  Geranium: require("../../assets/Crops/Geranium.jpg"),
  Gerbera: require("../../assets/Crops/Gerbera.jpg"),
  "German Turnip": require("../../assets/Crops/German Turnip.png"),
  Gherkins: require("../../assets/Crops/Gherkins.png"),
  Ginger: require("../../assets/Crops/Ginger.png"),
  Gladiolus: require("../../assets/Crops/Gladiolus.jpg"),
  Gliricidia: require("../../assets/Crops/Gliricidia.jpg"),
  Gram: require("../../assets/Crops/Gram.png"),
  Grape: require("../../assets/Crops/Grape.jpg"),
  Grapes: require("../../assets/Crops/Grapes.jpg"),
  "Greater yam": require("../../assets/Crops/Greater yam.jpeg"),
  "Green Cardamom": require("../../assets/Crops/Green Cardamom.jpg"),
  "Green Chilli": require("../../assets/Crops/Green Chilli.png"),
  "Green Gram": require("../../assets/Crops/Green Gram.png"),
  "Green Gram, Golden gram": require("../../assets/Crops/Green Gram.png"),
  "Green Mango": require("../../assets/Crops/Green Mango.jpg"),
  "Green Papaya": require("../../assets/Crops/Green Papaya.jpg"),
  "Green Pea": require("../../assets/Crops/Green Pea.jpg"),
  "Greeng Gram": require("../../assets/Crops/Green Gram.png"),
  "Green Peas": require("../../assets/Crops/Green Peas.jpg"),
  "Ground Nut": require("../../assets/Crops/Ground Nut.png"),
  GroundNut: require("../../assets/Crops/GroundNut.png"),
  Guava: require("../../assets/Crops/Guava.jpg"),
  "Guinea grass": require("../../assets/Crops/Guinea grass.jpg"),
  "Gymnema (Sugar destroyer)": require("../../assets/Crops/Gymnema (Sugar destroyer).jpg"),
  "Hedge lucerne": require("../../assets/Crops/Hedge lucerne.jpg"),
  Heliconia: require("../../assets/Crops/Heliconia.jpg"),
  Hogplum: require("../../assets/Crops/Hogplum.png"),
  "Holy basil": require("../../assets/Crops/Holy basil.jpeg"),
  "Honey Plant": require("../../assets/Crops/Honey Plant.png"),
  Hops: require("../../assets/Crops/Hops.jpg"),
  "Horse Gram": require("../../assets/Crops/Horse Gram.jpg"),
  "Horsegram": require("../../assets/Crops/Horse Gram.jpg"),
  "Hyacinth Bean": require("../../assets/Crops/Hyacinth Bean.jpeg"),
  "Hyacinth Bean or Lablab Bean": require("../../assets/Crops/Hyacinth Bean.jpeg"),
  "Hybrid napier": require("../../assets/Crops/Hybrid napier.jpeg"),
  "Indian Beech": require("../../assets/Crops/Indian Beech.jpg"),
  "Indian Beech Tree": require("../../assets/Crops/Indian Beech.jpg"),
   "Indian Beech / Pongam Tree": require("../../assets/Crops/Indian Beech.jpg"),
  "Indian Blackberry": require("../../assets/Crops/Indian Blackberry.jpg"),
  "Indian Butter Tree / Mahua": require("../../assets/Crops/Indian Butter Tree.jpg"),
  "Indian Gooseberry": require("../../assets/Crops/Indian Gooseberry.jpg"),
  "Indian Gooseberry (Amla)": require("../../assets/Crops/Indian Gooseberry.jpg"),
  "Indian hogweed / Spiny amaranth": require("../../assets/Crops/Indian hogweed.jpg"),
  "Indian Jujube (Ber)": require("../../assets/Crops/Indian Jujube.jpeg"),
  "Indian mustard": require("../../assets/Crops/Indian mustard.jpg"),
  "Indian sarsaparilla (Mangani root)": require("../../assets/Crops/Indian sarsaparilla.jpeg"),
  Indigo: require("../../assets/Crops/Indigo.jpg"),
  Irul: require("../../assets/Crops/Irul.png"),
  "Ivy Gourd": require("../../assets/Crops/Ivy Gourd.jpg"),
  Jack: require("../../assets/Crops/Jack.jpg"),
  "Jack Fruit": require("../../assets/Crops/Jack.jpg"),
  JackFruit: require("../../assets/Crops/Jack.jpg"),
  Jamun: require("../../assets/Crops/Jamun.jpg"),
  "Jamun fruit": require("../../assets/Crops/Jamun.jpg"),
  "Japanese Persimmon": require("../../assets/Crops/Japanese Persimmon.jpg"),
  Jasmine: require("../../assets/Crops/Jasmine.jpg"),
  Jeevakom: require("../../assets/Crops/Jeevakom.png"),
  Jicama: require("../../assets/Crops/Jicama.jpeg"),
  "Jute Leaves": require("../../assets/Crops/Jute Leaves.jpeg"),
  Kacholam: require("../../assets/Crops/Kacholam.png"),
  "Kagzi Lime": require("../../assets/Crops/Kagzi Lime.png"),
  "Kalai Dal": require("../../assets/Crops/Kalai Dal.png"),
  Kampakam: require("../../assets/Crops/Kampakam.jpg"),
  Kanjiram: require("../../assets/Crops/Kanjiram.png"),
  Karinochi: require("../../assets/Crops/Karinochi.jpg"),
  Karonda: require("../../assets/Crops/Karonda.jpeg"),
  "Kashi kanagile": require("../../assets/Crops/Kashi kanagile.jpg"),
  Kasthurimanjal: require("../../assets/Crops/Kasthurimanjal.jpg"),
  Kattarvazha: require("../../assets/Crops/Kattarvazha.jpg"),
  "Kidney Bean": require("../../assets/Crops/Kidney Bean.png"),
  "Kidney Bean/Rajama": require("../../assets/Crops/Kidney Bean.png"),
  "Kinnow (mandarin)": require("../../assets/Crops/Kinnow.png"),
  Kiwifruit: require("../../assets/Crops/Kiwifruit.png"),
  "Knol-khol": require("../../assets/Crops/Knol-khol.png"),
  "Kodo millet": require("../../assets/Crops/Kodo millet.jpg"),
  Kokum: require("../../assets/Crops/Kokum.png"),
  Koovalam: require("../../assets/Crops/Koovalam.jpg"),
  Kurumthotti: require("../../assets/Crops/Kurumthotti.jpg"),
  Kusuma: require("../../assets/Crops/Kusuma.jpg"),
  "Lady's Finger": require("../../assets/Crops/Lady's Finger.jpeg"),
  "Large Cardamom": require("../../assets/Crops/Large Cardamom.png"),
  "largeShah Marich": require("../../assets/Crops/largeShah Marich.jpg"),
  Lemon: require("../../assets/Crops/Lemon.jpg"),
  Lemongrass: require("../../assets/Crops/Lemongrass.jpg"),
  Lentil: require("../../assets/Crops/Lentil.png"),
  "Lesser yarm": require("../../assets/Crops/Lesser yarm.png"),
  Lettuce: require("../../assets/Crops/Lettuce.png"),
  "Lime / Lemon": require("../../assets/Crops/Lime Lemon.jpg"),
  "Linseed": require("../../assets/Crops/Linseed.jpg"),
  "Linseed, flax": require("../../assets/Crops/Linseed.jpg"),
  Litchi: require("../../assets/Crops/Litchi.png"),
  "Little Millet": require("../../assets/Crops/Little Millet.png"),
  "Long melon": require("../../assets/Crops/Long melon.jpg"),
  "Long pepper": require("../../assets/Crops/Long pepper.png"),
  Loquat: require("../../assets/Crops/Loquat.jpg"),
  Lucerne: require("../../assets/Crops/Lucerne.jpg"),
  Mahagony: require("../../assets/Crops/Mahagony.jpg"),
  Mahogany: require("../../assets/Crops/Mahagony.jpg"),
  Maize: require("../../assets/Crops/Maize.jpg"),
  "Malabar Neem": require("../../assets/Crops/Malabar Neem.jpeg"),
  Mandarin: require("../../assets/Crops/Mandarin.png"),
  "Mandarin orange": require("../../assets/Crops/Mandarin.png"),
  Mangium: require("../../assets/Crops/Mangium.jpg"),
  Mango: require("../../assets/Crops/Mango.jpg"),
  "Mango-ginger": require("../../assets/Crops/Mango-ginger.jpg"),
  Mangosteen: require("../../assets/Crops/Mangosteen.png"),
  Marigold: require("../../assets/Crops/Marigold.jpg"),
  Mash: require("../../assets/Crops/Mash.png"),
  "Matar Dal (Split peas)": require("../../assets/Crops/Matar Dal.jpg"),
  Mentha: require("../../assets/Crops/Mentha.jpg"),
  Mesta: require("../../assets/Crops/Mesta.jpeg"),
  Millet: require("../../assets/Crops/Millet.jpg"),
  Moong: require("../../assets/Crops/Moong.png"),
  "Moong Dal": require("../../assets/Crops/Moong.png"),
  "Moth Bean": require("../../assets/Crops/Moth Bean.png"),
  "Mung": require("../../assets/Crops/Moong.png"),
  "Mung bean": require("../../assets/Crops/Moong.png"),
  "Mustard": require("../../assets/Crops/Mustard.jpg"),
  Mushroom: require("../../assets/Crops/Mushroom.png"),
  Muskmelon: require("../../assets/Crops/Muskmelon.jpg"),
  "Musur Dal": require("../../assets/Crops/Musur Dal.png"),
  "Napier Grass": require("../../assets/Crops/Napier Grass.jpg"),
  "Neela amari": require("../../assets/Crops/Neela amari.jpg"),
  Neem: require("../../assets/Crops/Neem.jpg"),
  "Neem (ground type)": require("../../assets/Crops/Neem.jpg"),
  "Nilappana": require("../../assets/Crops/Nilappana.jpg"),
  Niger: require("../../assets/Crops/Niger.jpeg"),
  Nutmeg: require("../../assets/Crops/Nutmeg.png"),
  Oat: require("../../assets/Crops/Oat.jpg"),
  Oats: require("../../assets/Crops/Oat.jpg"),
  Oilpalm: require("../../assets/Crops/Oilpalm.jpg"),
  Okra: require("../../assets/Crops/Okra.jpeg"),
  "Okra (Lady\u2019s finger)": require("../../assets/Crops/Okra.jpeg"),
  "Olea europaea": require("../../assets/Crops/Olea europaea.jpg"),
  "Olive": require("../../assets/Crops/Olea europaea.jpg"),
  Onion: require("../../assets/Crops/Onion.png"),
  Orange: require("../../assets/Crops/Orange.jpeg"),
  "Orange (Sweet Orange / Mosambi)": require("../../assets/Crops/Orange.jpeg"),
  Orchids: require("../../assets/Crops/Orchids.png"),
  "Oryza sativa": require("../../assets/Crops/Oryza sativa.jpeg"),
  Palmarosa: require("../../assets/Crops/Palmarosa.png"),
  "Palmarosa grass": require("../../assets/Crops/Palmarosa.png"),
  Paddy: require("../../assets/Crops/Paddy.jpg"),
  "Palmyra palm": require("../../assets/Crops/Palmyra palm.jpg"),
  "Paddy/Rice": require("../../assets/Crops/Paddy.jpg"),
  Papaya: require("../../assets/Crops/Papaya.jpg"),
  "Para grass": require("../../assets/Crops/Para grass.jpg"),
  "Paradise tree": require("../../assets/Crops/Paradise tree.jpg"),
  "Passion fruit": require("../../assets/Crops/Passion fruit.jpg"),
  Patchouli: require("../../assets/Crops/Patchouli.png"),
  Pathimugham: require("../../assets/Crops/Pathimugham.png"),
  pea: require("../../assets/Crops/pea.jpg"),
  Peach: require("../../assets/Crops/Peach.jpg"),
  Pear: require("../../assets/Crops/Pear.jpg"),
  "Pearl Millet": require("../../assets/Crops/Pearl Millet.jpg"),
  "Pecan Nut": require("../../assets/Crops/Pecan Nut.jpg"),
  "Physic Nut / Jatropha": require("../../assets/Crops/Physic Nut Jatropha.jpeg"),
  "Pickling melon": require("../../assets/Crops/Pickling melon.jpg"),
  "Pigeon Pea": require("../../assets/Crops/Pigeon Pea.jpg"),
  "Pigeon Pea, Red gram": require("../../assets/Crops/Pigeon Pea.jpg"),
  Pineapple: require("../../assets/Crops/Pineapple.jpeg"),
  Plum: require("../../assets/Crops/Plum.jpg"),
  "Pointed Gourd": require("../../assets/Crops/Pointed Gourd.png"),
  Pomegranate: require("../../assets/Crops/Pomegranate.jpg"),
  Potato: require("../../assets/Crops/Potato.jpg"),
  "Proso millet": require("../../assets/Crops/Proso millet.jpg"),
  "Proso milllet": require("../../assets/Crops/Proso millet.jpg"),
  Pumpkin: require("../../assets/Crops/Pumpkin.jpg"),
  Punna: require("../../assets/Crops/Punna.jpg"),
  Quina: require("../../assets/Crops/Quina.png"),
  Raddish: require("../../assets/Crops/Raddish.jpg"),
  Radish: require("../../assets/Crops/Raddish.jpg"),
  Ragi: require("../../assets/Crops/Ragi.png"),
  Ramboothan: require("../../assets/Crops/Ramboothan.jpeg"),
  Ramphal: require("../../assets/Crops/Ramphal.jpeg"),
  "Rapeseed and Mustard": require("../../assets/Crops/Rapeseed and Mustard.jpeg"),
  "Raw Bengal Gram": require("../../assets/Crops/Raw Bengal Gram.png"),
  "Red Chilli": require("../../assets/Crops/Red Chilli.png"),
  "Red Gram/Pigeon Pea": require("../../assets/Crops/Red gram.png"),
  "Red Gram": require("../../assets/Crops/Red gram.png"),
  "Red Sandalwood": require("../../assets/Crops/Red Sandalwood.png"),
  "Red Sanders / Red Sandalwood": require("../../assets/Crops/Red Sandalwood.png"),
  Rice: require("../../assets/Crops/Rice.jpeg"),
   "Rice (Paddy)": require("../../assets/Crops/Rice.jpeg"),
  "Ridge Gourd": require("../../assets/Crops/Ridge Gourd.jpeg"),
  "Ripe Papaya": require("../../assets/Crops/Ripe Papaya.png"),
  Rose: require("../../assets/Crops/Rose.png"),
  "Rose (Greenhouse)": require("../../assets/Crops/Rose.png"),
  Roselle: require("../../assets/Crops/Roselle.jpg"),
  "Roselle / Red sorrel": require("../../assets/Crops/Roselle.jpg"),
  Rosemary: require("../../assets/Crops/Rosemary.jpg"),
  Rosewood: require("../../assets/Crops/Rosewood.jpeg"),
  "Round gourd": require("../../assets/Crops/Round gourd.png"),
  Rubber: require("../../assets/Crops/Rubber.jpeg"),
  Ryegrass: require("../../assets/Crops/Ryegrass.jpg"),
  "Safed musli": require("../../assets/Crops/Safed musli.jpg"),
  Safflower: require("../../assets/Crops/Safflower.jpeg"),
  Sandal: require("../../assets/Crops/Sandal.jpeg"),
  Sandalwood: require("../../assets/Crops/Sandal.jpeg"),
  "Sapodilla (chiku)": require("../../assets/Crops/Sapodilla.jpeg"),
  Sapota: require("../../assets/Crops/Sapota.jpeg"),
  "Sarpagandha (Indian snakeroot)": require("../../assets/Crops/Sarpagandha.jpg"),
  Senji: require("../../assets/Crops/Senji.jpg"),
  Sesame: require("../../assets/Crops/Sesame.jpg"),
  "Sesame, Gingelly": require("../../assets/Crops/Sesame.jpg"),
  "Setaria grass": require("../../assets/Crops/Setaria grass.jpg"),
  "Shah marich": require("../../assets/Crops/Shah marich.jpg"),
  Shaftal: require("../../assets/Crops/Shaftal.jpg"),
  Shevri: require("../../assets/Crops/Shevri.jpeg"),
  "Snake Gourd": require("../../assets/Crops/Snake Gourd.jpeg"),
  Sorghum: require("../../assets/Crops/Sorghum.png"),
  "Sorghum (Fodder)": require("../../assets/Crops/Sorghum.png"),
  "Sorghum (Rabi/Kharif)": require("../../assets/Crops/Sorghum.png"),
  Soyabean: require("../../assets/Crops/Soyabean.jpeg"),
  Soybean: require("../../assets/Crops/Soyabean.jpeg"),
  Spinach: require("../../assets/Crops/Spinach.png"),
  "Sponge gourd": require("../../assets/Crops/Sponge gourd.jpg"),
  Squash: require("../../assets/Crops/Squash.jpeg"),
  Stevia: require("../../assets/Crops/Stevia.png"),
  Strawberry: require("../../assets/Crops/Strawberry.png"),
  Stylo: require("../../assets/Crops/Stylo.png"),
  Subabul: require("../../assets/Crops/Subabul.jpg"),
  Sugarbeet: require("../../assets/Crops/Sugarbeet.png"),
  Sugarcane: require("../../assets/Crops/Sugarcane.jpeg"),
  "Summer squash": require("../../assets/Crops/Summer squash.jpg"),
  "Sun hemp": require("../../assets/Crops/Sun hemp.jpg"),
  Sunflower: require("../../assets/Crops/Sunflower.jpg"),
  "Sweet Cherry": require("../../assets/Crops/Sweet Cherry.jpg"),
  "Sweet Lemon": require("../../assets/Crops/Sweet Lemon.jpg"),
  "Sweet Lime": require("../../assets/Crops/Sweet Lime.png"),
  "Sweet orange": require("../../assets/Crops/Sweet orange.png"),
  "Sweet pepper": require("../../assets/Crops/Sweet pepper.jpg"),
  "Sweet potato": require("../../assets/Crops/Sweet potato.jpg"),
  Tamarind: require("../../assets/Crops/Tamarind.jpg"),
  Tapioca: require("../../assets/Crops/Tapioca.jpg"),
  Tea: require("../../assets/Crops/Tea.jpeg"),
  Teak: require("../../assets/Crops/Teak.jpeg"),
  Thembavu: require("../../assets/Crops/Thembavu.png"),
  Thippali: require("../../assets/Crops/Thippali.png"),
  "Thorny bamboo": require("../../assets/Crops/Thorny bamboo.png"),
  Thulasi: require("../../assets/Crops/Thulasi.jpeg"),
  "Tulsi (Holy basil)": require("../../assets/Crops/Thulasi.jpeg"),
  Tobacco: require("../../assets/Crops/Tobacco.jpg"),
  Tomato: require("../../assets/Crops/Tomato.jpg"),
  "Tree Tomato": require("../../assets/Crops/Tree Tomato.jpg"),
  Tuberose: require("../../assets/Crops/Tuberose.png"),
  Turmeric: require("../../assets/Crops/Turmeric.png"),
  Turnip: require("../../assets/Crops/Turnip.png"),
  Urd: require("../../assets/Crops/Urd.jpg"),
  Vanilla: require("../../assets/Crops/Vanilla.jpg"),
  "Vegetable cowpea": require("../../assets/Crops/Vegetable cowpea.jpg"),
  Venga: require("../../assets/Crops/Venga.jpg"),
  Vetiver: require("../../assets/Crops/Vetiver.jpeg"),
  "Vetiver (Khus grass)": require("../../assets/Crops/Vetiver.jpeg"),
  Walnut: require("../../assets/Crops/Walnut.jpg"),
  Wanga: require("../../assets/Crops/Wanga.jpeg"),
  "Water melon": require("../../assets/Crops/Water melon.jpg"),
  "Watermelon": require("../../assets/Crops/Water melon.jpg"),
  "West Indian Cherry": require("../../assets/Crops/West Indian Cherry.jpeg"),
  Wheat: require("../../assets/Crops/Wheat.jpg"),
  "White yam": require("../../assets/Crops/White yam.png"),
  "Wild date palm": require("../../assets/Crops/Wild date palm.jpg"),
  "Wild indigo": require("../../assets/Crops/Wild indigo.jpeg"),
  "Wild jack or Aini": require("../../assets/Crops/Wild jack or Aini.jpeg"),
  "Wild Tamarind": require("../../assets/Crops/Wild Tamarind.jpg"),
  "Wood apple": require("../../assets/Crops/Wood apple.jpeg"),
  Yam: require("../../assets/Crops/Yam.jpeg"),
};

// Pre-compute a lowercase lookup once for fast matching.
const _lower: Record<string, ImageSourcePropType> = {};
for (const k of Object.keys(_map)) {
  _lower[k.toLowerCase()] = _map[k];
}

// Normalise a crop name for matching:
//   - lower-case
//   - strip parentheses and slashes
//   - collapse whitespace
function normalise(name: string): string {
  return name.toLowerCase().replace(/[()]/g, "").replace(/\s+/g, " ").trim();
}

/**
 * Returns the image source for a crop name, or null if no matching
 * image is bundled. Matching is case-insensitive and tolerant of
 * minor punctuation differences (e.g. "Bajra/Pearl millet" →
 * "Bajra Pearl millet.jpg").
 */
export function getCropImage(cropName: string): ImageSourcePropType | null {
  if (!cropName) return null;
  // 1. Exact match (fastest path).
  if (_map[cropName]) return _map[cropName];
  // 2. Case-insensitive exact match.
  const lower = cropName.toLowerCase();
  if (_lower[lower]) return _lower[lower];
  // 3. Normalised match (strips "(", ")", "/", extra spaces).
  const norm = normalise(cropName);
  for (const k of Object.keys(_lower)) {
    if (normalise(k) === norm) return _lower[k];
  }
  return null;
}
