/**
 * onDeviceAI.ts — On-Device AI Validation Pipeline
 *
 * Runs locally on the mobile client before submission to catch issues
 * immediately without waiting for a server round-trip. Falls through
 * gracefully if device capability checks fail; never blocks submission
 * on browser environments that lack required APIs.
 *
 * Pipeline order:
 *   1. Spam detection      — pattern-based, synchronous
 *   2. Agriculture relevance — keyword + signal scoring
 *   3. Duplicate detection — exact (normalised) + semantic similarity via
 *                             Levenshtein ratio against a local question cache
 *      persisted in AsyncStorage
 *
 * Each stage emits a result object; the pipeline aggregates them into a
 * single AIValidationResult that QuestionScreen consumes to decide whether
 * to show a warning banner or proceed directly to the preview API call.
 */

import AsyncStorage from '@react-native-async-storage/async-storage';
import { Platform } from 'react-native';
import { SIMILARITY_THRESHOLD } from './constants';

// ─── Types ─────────────────────────────────────────────────────────────────────

export interface AIValidationResult {
  /** Overall PASS / WARN / FAIL — WARN means show banner, FAIL blocks submit */
  verdict: 'pass' | 'warn' | 'fail';
  /** Human-readable message suitable for a Toast / banner */
  message: string | null;
  /** Key into locales for the rejection reason (i18n-aware) */
  reasonKey: string | null;
  /** Individual stage outcomes */
  stages: {
    relevance:  StageResult;
    duplicate:  StageResult;
    spam:       StageResult;
  };
  /** True when at least one stage ran; false = device unsupported */
  ran: boolean;
}

export interface StageResult {
  /** Whether this stage passed all checks */
  pass: boolean;
  /** Confidence 0–1 */
  confidence: number;
  /** Optional short description for debug display */
  detail?: string;
}

interface CachedQuestion {
  id: string;
  text: string;
  /** ISO date string — used for TTL eviction */
  cachedAt: string;
}

// ─── Constants ─────────────────────────────────────────────────────────────────

const DUPLICATE_CACHE_KEY = 'on_device_ai_duplicate_cache';
const DUPLICATE_CACHE_MAX_ENTRIES = 50;
const /** ms */ DUPLICATE_CACHE_TTL_MS = 7 * 24 * 60 * 60 * 1_000; // 7 days

// ─── Agriculture Relevance ─────────────────────────────────────────────────────

/**
 * Broad agricultural keyword set spanning crops, livestock, irrigation,
 * fertilisers, pesticides, weather, soil, and post-harvest topics.
 * Covers all major Indian languages and English so that code-switched
 * or transliterated input still scores relevance.
 */
const AGRICULTURE_KEYWORDS = new Set([
  // ── Crops ──────────────────────────────────────────────────────────────────
  "wheat",
  "rice",
  "paddy",
  "maize",
  "bajra",
  "jowar",
  "ragi",
  "barley",
  "cotton",
  "sugarcane",
  "groundnut",
  "mustard",
  "soybean",
  "sunflower",
  "sesame",
  "castor",
  "linseed",
  "niger",
  "gram",
  "tur",
  "masoor",
  "moong",
  "urad",
  "horsegram",
  "lentil",
  "peas",
  "beans",
  "soyabean",
  "soyabeen",
  "arhar",
  "khesari",
  "chickpea",
  "pigeonpea",
  "tomato",
  "potato",
  "onion",
  "garlic",
  "ginger",
  "turmeric",
  "chilli",
  "brinjal",
  "cabbage",
  "cauliflower",
  "okra",
  "bhindi",
  "ladyfinger",
  "cucumber",
  "gourd",
  "pumpkin",
  "bottle gourd",
  "bitter gourd",
  "ridge gourd",
  "carrot",
  "radish",
  "beetroot",
  "spinach",
  "lettuce",
  "fenugreek",
  "coriander",
  "cumin",
  "fennel",
  "coriander seeds",
  "carom",
  "ajwain",
  "black pepper",
  "cardamom",
  "cinnamon",
  "cloves",
  "nutmeg",
  "mango",
  "banana",
  "grape",
  "citrus",
  "orange",
  "mosambi",
  "lime",
  "lemon",
  "apple",
  "pear",
  "peach",
  "plum",
  "apricot",
  "litchi",
  "guava",
  "papaya",
  "pomegranate",
  "date",
  "fig",
  "jackfruit",
  "jamun",
  "ber",
  "karonda",
  "coconut",
  "arecanut",
  "cashew",
  "almond",
  "walnut",
  "pistachio",
  "coffee",
  "tea",
  "rubber",
  "rose",
  "marigold",
  "jasmine",
  "tuberose",
  "carnation",
  "orchid",
  "drumstick",
  "moriga",
  "moringa",
  "tamarind",
  "bamboo",
  "neem",
  "teak",
  "jute",
  "mesta",
  "sunhemp",
  "dhaincha",
  // ── Additional Crops ────────────────────────────────────────────────────────
  "sorghum",
  "finger millet",
  "pearl millet",
  "foxtail millet",
  "kodo millet",
  "little millet",
  "barnyard millet",
  "proso millet",
  "amaranth",
  "quinoa",
  "buckwheat",
  "oats",
  "triticale",
  "spelt",
  "cowpea",
  "field bean",
  "faba bean",
  "kidney bean",
  "french bean",
  "clusterbean",
  "guar",
  "moth bean",
  "rice bean",
  "velvet bean",
  "lab lab",
  "safflower",
  "rapeseed",
  "canola",
  "flaxseed",
  "hemp",
  "ramie",
  "tobacco",
  "indigo",
  "henna",
  "pyrethrum plant",
  "sweet potato",
  "yam",
  "colocasia",
  "tapioca",
  "cassava",
  "arrowroot",
  "elephant foot yam",
  "greater yam",
  "amorphophallus",
  "ash gourd",
  "snake gourd",
  "ivy gourd",
  "pointed gourd",
  "parwal",
  "tinda",
  "round melon",
  "watermelon",
  "muskmelon",
  "cantaloupe",
  "drumstick leaves",
  "curry leaves",
  "amaranth leaves",
  "bathua",
  "purslane",
  "brahmi",
  "safed musli",
  "shatavari",
  "ashwagandha",
  "tulsi",
  "stevia",
  "lemon grass",
  "citronella",
  "palmarosa",
  "vetiver",
  "khus",
  "lavender",
  "chamomile",
  "aloe vera",
  "kalmegh",
  "isabgol",
  "psyllium",
  "senna",
  "cassia",
  "belladonna",
  "paprika",
  "chilli pepper",
  "capsicum",
  "bell pepper",
  "kiwi",
  "avocado",
  "passion fruit",
  "dragon fruit",
  "strawberry",
  "raspberry",
  "blackberry",
  "mulberry",
  "gooseberry",
  "amla",
  "bael",
  "wood apple",
  "star fruit",
  "carambola",
  "sapota",
  "chikoo",
  "loquat",
  "pineapple",
  "custard apple",
  "sitaphal",
  "ramphal",
  "durian",
  "rambutan",
  "mangosteen",
  "soursop",
  "breadfruit",
  "betel leaf",
  "paan",
  "vanilla",
  "saffron",
  "mace",
  "star anise",
  "bay leaf",
  "curry leaf",
  "kokum",
  "garcinia",
  "eucalyptus",
  "poplar",
  "subabul",
  "leucaena",
  "acacia",
  "casuarina",
  "silver oak",
  "ailanthus",
  "paulownia",
  "chrysanthemum",
  "gladiolus",
  "dahlia",
  "anthurium",
  "heliconia",
  "gerbera",
  "lilium",
  "lotus",
  "water lily",
  "bird of paradise",
  "sunflower seed",
  "niger seed",
  "hemp seed",

  // ── Animals / Livestock ─────────────────────────────────────────────────────
  "cattle",
  "buffalo",
  "cow",
  "bull",
  "ox",
  "calf",
  "goat",
  "sheep",
  "lamb",
  "poultry",
  "chicken",
  "broiler",
  "layer",
  "duck",
  "quail",
  "pigeon",
  "pig",
  "swine",
  "rabbit",
  "fish",
  "prawn",
  "shrimp",
  "crab",
  "milk",
  "dairy",
  "colostrum",
  "butter",
  "ghee",
  "curd",
  "cheese",
  "breeding",
  "insemination",
  "ai",
  "artificial insemination",
  "pregnancy",
  "calving",
  "lactation",
  "milking",
  "mastitis",
  "fmd",
  "foot and mouth",
  "hs",
  "haemorrhagic septicaemia",
  "bse",
  "lumpy skin",
  "fmdv",
  "deworming",
  "vaccination",
  "vaccine",
  "anthrax",
  "rabies",
  "fodder",
  "feed",
  "silage",
  "hay",
  "straw",
  "concentrate",
  "mineral mixture",
  "crutching",
  "shearing",
  "hoof",
  "hoof trimming",
  // ── Additional Livestock & Poultry ─────────────────────────────────────────
  "heifer",
  "steer",
  "bullock",
  "zebu",
  "jersey",
  "holstein",
  "murrah",
  "gir cow",
  "sahiwal",
  "tharparkar",
  "kankrej",
  "ongole",
  "red sindhi",
  "nili ravi",
  "surti",
  "jaffarabadi",
  "mehsana",
  "beetal goat",
  "jamnapari",
  "barbari",
  "sirohi",
  "osmanabadi",
  "malabari goat",
  "attappady goat",
  "black bengal goat",
  "merino",
  "corriedale",
  "deccani",
  "marwari sheep",
  "nellore sheep",
  "dorper",
  "suffolk",
  "rambouillet",
  "turkey",
  "goose",
  "guinea fowl",
  "emu",
  "ostrich",
  "peacock",
  "silkie",
  "kadaknath",
  "aseel",
  "naked neck",
  "giriraj",
  "khaki campbell",
  "muscovy duck",
  "pekin duck",
  "japanese quail",
  "bobwhite quail",
  "horse",
  "mare",
  "stallion",
  "foal",
  "pony",
  "donkey",
  "mule",
  "camel",
  "yak",
  "mithun",
  "gayal",
  "dog",
  "cat",
  "pet animal",
  "honeybee",
  "apis mellifera",
  "apis cerana",
  "apis dorsata",
  "silkworm",
  "sericulture",
  "mulberry silk",
  "tasar",
  "eri",
  "muga silk",
  "lac insect",
  "lac cultivation",
  "shellac",
  "earthworm",
  "vermicompost worm",
  "eisenia fetida",
  "freshwater fish",
  "catfish",
  "rohu",
  "catla",
  "mrigal",
  "grass carp",
  "silver carp",
  "common carp",
  "tilapia",
  "pangasius",
  "singhi",
  "magur",
  "murrel",
  "snakehead",
  "hilsa",
  "sardine",
  "mackerel",
  "pomfret",
  "tuna",
  "salmon",
  "trout",
  "seabass",
  "grouper",
  "lobster",
  "oyster",
  "mussel",
  "clam",
  "squid",
  "octopus",
  "aquaculture",
  "pisciculture",
  "fish pond",
  "fish seed",
  "fingerling",
  "hatchery",
  "fish meal",
  "fishmeal",
  "fish feed",
  "fry",
  "spawn",
  "nursery pond",
  "grow out pond",
  "layer farming",
  "broiler farming",
  "poultry litter",
  "poultry manure",
  "egg production",
  "egg incubation",
  "hatchability",
  "day old chick",
  "brooding",
  "brooder",
  "deep litter",
  "cage system",
  "free range",
  "livestock insurance",
  "animal husbandry",
  "veterinary",
  "animal feed",
  "total mixed ration",
  "tmr",
  "bypass protein",
  "bypass fat",
  "urea molasses",
  "molasses mineral block",
  "cattle shed",
  "loose housing",
  "stall feeding",
  "zero grazing",
  "pasture",
  "rangeland",
  "grazing",
  "rotational grazing",
  "milk yield",
  "fat percentage",
  "snf",
  "somatic cell count",
  "milk testing",
  "lactometer",
  "fat test",
  "milk adulteration",
  "estrus",
  "heat detection",
  "pregnancy diagnosis",
  "embryo transfer",
  "semen",
  "frozen semen",
  "semen straw",
  "liquid nitrogen",
  "castration",
  "dehorning",
  "ear tagging",
  "tattooing",
  "animal disease",
  "vet",
  "veterinarian",
  "animal clinic",
  "ppr",
  "peste des petits ruminants",
  "brucellosis",
  "tuberculosis",
  "black quarter",
  "bq",
  "enterotoxaemia",
  "newcastle disease",
  "nd",
  "infectious bursal disease",
  "ibd",
  "marek disease",
  "fowl pox",
  "avian influenza",
  "bird flu",
  "salmonella",
  "coccidiosis",
  "worms",
  "liver fluke",
  "tapeworm",
  "roundworm",
  "tick",
  "lice",
  "mange",
  "ringworm",
  "ectoparasite",
  "endoparasite",
  "parasite",

  // ── Soil & Nutrient Management ──────────────────────────────────────────────
  "soil",
  "soil testing",
  "soil health",
  "n p k",
  "nitrogen",
  "phosphorus",
  "potash",
  "potassium",
  "urea",
  "dap",
  "npk",
  "ammonium",
  "compost",
  "fym",
  "farmyard manure",
  "vermicompost",
  "bio-fertilizer",
  "biofertilizer",
  "rhizobium",
  "azolla",
  "psb",
  "mycorrhiza",
  "lime",
  "liming",
  "gypsum",
  "sulfur",
  "micronutrient",
  "zinc",
  "iron",
  "boron",
  "manganese",
  "copper",
  "molybdenum",
  "chlorosis",
  "organic",
  "organic farming",
  "natural farming",
  "zero budget",
  "jeevamrut",
  "jeevamrit",
  "beejamrit",
  "ghana jeevamrit",
  "cow dung",
  "composting",
  "wormicompost",
  "green manure",
  "green manuring",
  "mulch",
  "mulching",
  "straw mulch",
  "plastic mulch",
  // ── Additional Soil & Nutrition ─────────────────────────────────────────────
  "soil ph",
  "soil acidity",
  "soil alkalinity",
  "saline soil",
  "sodic soil",
  "saline sodic soil",
  "reclamation",
  "soil reclamation",
  "calcium",
  "magnesium",
  "sulphur",
  "silicon",
  "selenium",
  "cobalt",
  "sodium",
  "chlorine",
  "secondary nutrient",
  "macro nutrient",
  "micro nutrient",
  "nutrient deficiency",
  "nutrient toxicity",
  "leaf analysis",
  "tissue test",
  "cation exchange capacity",
  "cec",
  "base saturation",
  "soil organic matter",
  "soil organic carbon",
  "humus",
  "humic acid",
  "fulvic acid",
  "amino acid",
  "seaweed extract",
  "fish hydrolysate",
  "liquid fertilizer",
  "water soluble fertilizer",
  "wsf",
  "controlled release fertilizer",
  "crf",
  "enhanced efficiency fertilizer",
  "urease inhibitor",
  "nitrification inhibitor",
  "soil texture",
  "loam",
  "sandy loam",
  "clay loam",
  "silty loam",
  "clay",
  "sand",
  "silt",
  "gravel",
  "coarse soil",
  "fine soil",
  "soil structure",
  "aggregate stability",
  "bulk density",
  "porosity",
  "water holding capacity",
  "field capacity",
  "wilting point",
  "soil profile",
  "topsoil",
  "subsoil",
  "hardpan",
  "plough pan",
  "laterite soil",
  "black soil",
  "red soil",
  "alluvial soil",
  "desert soil",
  "acidic soil",
  "alkaline soil",
  "neutral soil",
  "vertisol",
  "inceptisol",
  "soil erosion",
  "water erosion",
  "wind erosion",
  "sheet erosion",
  "rill erosion",
  "gully erosion",
  "landslide",
  "soil conservation",
  "contour bund",
  "contour farming",
  "bench terrace",
  "check dam",
  "stone bund",
  "grass waterway",
  "vegetative barrier",
  "windbreak",
  "nitrogen fixation",
  "biological nitrogen fixation",
  "bnf",
  "azotobacter",
  "azospirillum",
  "frankia",
  "cyanobacteria",
  "blue green algae",
  "phosphate solubilizing bacteria",
  "potassium solubilizing bacteria",
  "soil microbiome",
  "soil microbiology",
  "soil enzyme",
  "soil respiration",
  "earthworm count",
  "soil biodiversity",
  "food web",
  "nematode count",
  "panchagavya",
  "agniastra",
  "brahmastra",
  "dashaparni",
  "neem ark",
  "vermiwash",
  "biochar",
  "activated charcoal",
  "terra preta",
  "crop nutrition",
  "plant nutrition",
  "nutrient uptake",
  "root exudate",

  // ── Irrigation & Water ──────────────────────────────────────────────────────
  "irrigation",
  "drip",
  "drip irrigation",
  "sprinkler",
  "flood irrigation",
  "furrow",
  "check basin",
  "ridge and furrow",
  "drip system",
  "micro irrigation",
  "microirrigation",
  "pipe",
  "pipe layout",
  "pump",
  "motor",
  "borewell",
  "bore well",
  "open well",
  "well",
  "canal",
  "reservoir",
  "pond",
  "rainwater",
  "rain water",
  "harvesting",
  "water table",
  "drainage",
  "drainage system",
  "subsoil drainage",
  "drought",
  "drought resistant",
  "drought tolerant",
  "water stress",
  "moisture",
  "moisture conservation",
  "polythene",
  // ── Additional Irrigation & Water ───────────────────────────────────────────
  "submain",
  "lateral pipe",
  "emitter",
  "dripper",
  "micro tube",
  "fogger nozzle",
  "rain gun",
  "mini sprinkler",
  "overhead irrigation",
  "sub surface drip",
  "buried drip",
  "porous pipe",
  "pitcher irrigation",
  "pot irrigation",
  "basin irrigation",
  "strip irrigation",
  "border strip",
  "surge irrigation",
  "alternate furrow",
  "skip furrow",
  "deficit irrigation",
  "regulated deficit",
  "scheduled irrigation",
  "crop water requirement",
  "et",
  "evapotranspiration",
  "penman monteith",
  "crop coefficient",
  "kc value",
  "reference et",
  "etc",
  "soil moisture sensor",
  "tensiometer",
  "gypsum block",
  "neutron probe",
  "time domain reflectometry",
  "tdr",
  "capacitance probe",
  "fertigation unit",
  "venturi injector",
  "fertilizer tank",
  "proportioner",
  "filter",
  "disc filter",
  "screen filter",
  "sand filter",
  "media filter",
  "pressure gauge",
  "pressure regulator",
  "air valve",
  "flushing valve",
  "lift irrigation",
  "gravity irrigation",
  "command area",
  "canal irrigation",
  "tank irrigation",
  "tank system",
  "percolation tank",
  "check dam",
  "nala bund",
  "farm pond",
  "percolation pond",
  "groundwater",
  "aquifer",
  "recharge",
  "water recharge",
  "watershed",
  "watershed management",
  "micro watershed",
  "catchment",
  "runoff",
  "water use efficiency",
  "wue",
  "irrigation efficiency",
  "distribution uniformity",
  "emitter uniformity",
  "application efficiency",
  "salinity",
  "electrical conductivity",
  "ec",
  "sodicity",
  "sar",
  "leaching",
  "leaching requirement",
  "leaching fraction",
  "water quality",
  "bore water quality",
  "water analysis",
  "water testing",
  "recycled water",
  "treated effluent",
  "sewage water",
  "flood control",
  "embankment",
  "bund",
  "field bund",
  "lift canal",
  "pump set",
  "centrifugal pump",
  "submersible pump",
  "solar pump",
  "solar powered irrigation",
  "electric pump",
  "diesel pump",

  // ── Plant Protection ────────────────────────────────────────────────────────
  "pesticide",
  "insecticide",
  "fungicide",
  "herbicide",
  "rodenticide",
  "neem oil",
  "pyrethrum",
  "biological control",
  "biocontrol",
  "biopesticide",
  "botanical pesticide",
  "ipm",
  "integrated pest management",
  "pest",
  "pests",
  "insect",
  "insects",
  "bug",
  "bugs",
  "aphid",
  "aphids",
  "whitefly",
  "white fly",
  "jassid",
  "leafhopper",
  "hopper",
  "thrips",
  "mealybug",
  "mealy bug",
  "scale insect",
  "borer",
  "fruit borer",
  "pod borer",
  "stem borer",
  "shoot borer",
  "gall midge",
  "termite",
  "termites",
  "nematode",
  "nematodes",
  "eelworm",
  "mite",
  "mites",
  "spider mite",
  "red spider",
  "yellow mite",
  "locust",
  "grasshopper",
  "caterpillar",
  "armyworm",
  "army worm",
  "disease",
  "diseases",
  "blight",
  "leaf blight",
  "brown spot",
  "rust",
  "leaf rust",
  "powdery mildew",
  "downy mildew",
  "alternaria",
  "fusarium",
  "phythium",
  "rhizoctonia",
  "bacterial wilt",
  "wilt",
  "rot",
  "root rot",
  "fruit rot",
  "collar rot",
  "soft rot",
  "spot",
  "leaf spot",
  "anthracnose",
  "canker",
  "smut",
  "bunt",
  "mosaic",
  "mosaic virus",
  "yellow mosaic",
  "leaf curl",
  "leafroll",
  "bacterial blight",
  "leaf burn",
  "sheath blight",
  "grain discoloration",
  // ── Additional Plant Protection ──────────────────────────────────────────────
  "organophosphate",
  "pyrethroid",
  "neonicotinoid",
  "carbamate",
  "organochlorine",
  "imidacloprid",
  "chlorpyrifos",
  "lambda cyhalothrin",
  "cypermethrin",
  "malathion",
  "dimethoate",
  "profenofos",
  "spinosad",
  "emamectin benzoate",
  "thiamethoxam",
  "acetamiprid",
  "clothianidin",
  "dinotefuran",
  "abamectin",
  "azadirachtin",
  "beauveria",
  "metarhizium",
  "verticillium",
  "trichoderma",
  "pseudomonas",
  "bacillus thuringiensis",
  "bt",
  "nuclear polyhedrosis virus",
  "npv",
  "granulovirus",
  "entomopathogen",
  "mancozeb",
  "copper oxychloride",
  "captan",
  "thiram",
  "zineb",
  "ziram",
  "carbendazim",
  "thiophanate methyl",
  "propiconazole",
  "tebuconazole",
  "hexaconazole",
  "difenconazole",
  "trifloxystrobin",
  "azoxystrobin",
  "metalaxyl",
  "fosetyl",
  "cymoxanil",
  "dimethomorph",
  "iprovalicarb",
  "glyphosate",
  "paraquat",
  "atrazine",
  "2 4 d",
  "pendimethalin",
  "metribuzin",
  "butachlor",
  "pretilachlor",
  "clodinafop",
  "fenoxaprop",
  "bispyribac",
  "cyhalofop",
  "imazethapyr",
  "metsulfuron",
  "weedicide",
  "weed killer",
  "selective herbicide",
  "non selective herbicide",
  "pre emergence",
  "post emergence",
  "pre plant",
  "fall armyworm",
  "spodoptera",
  "helicoverpa",
  "bollworm",
  "pink bollworm",
  "american bollworm",
  "spotted bollworm",
  "tobacco caterpillar",
  "diamond back moth",
  "dbm",
  "cabbage looper",
  "cutworm",
  "semi looper",
  "hairy caterpillar",
  "bihar hairy caterpillar",
  "red hairy caterpillar",
  "painted bug",
  "blister beetle",
  "weevil",
  "grain weevil",
  "rice weevil",
  "maize weevil",
  "pulse beetle",
  "callosobruchus",
  "khapra beetle",
  "flour beetle",
  "grain moth",
  "angoumois grain moth",
  "stored grain pest",
  "gall wasp",
  "gall fly",
  "agromyza",
  "leafminer",
  "mining fly",
  "fruit fly",
  "melon fly",
  "oriental fruit fly",
  "olive fly",
  "bark beetle",
  "longhorn beetle",
  "shot hole borer",
  "bark borer",
  "white grub",
  "white grubs",
  "root grub",
  "soil grub",
  "cockchafer",
  "june bug",
  "rhinoceros beetle",
  "rice hispa",
  "rice bug",
  "rice skipper",
  "rice caseworm",
  "rice leafroller",
  "gundhi bug",
  "spilosoma",
  "citrus canker",
  "citrus greening",
  "citrus psylla",
  "tristeza",
  "sheath rot",
  "false smut",
  "bakanae",
  "blast",
  "rice blast",
  "neck blast",
  "tungro",
  "grassy stunt",
  "ragged stunt",
  "late blight",
  "early blight",
  "common scab",
  "bacterial soft rot",
  "charcoal rot",
  "sclerotinia rot",
  "white mold",
  "damping off",
  "seedling blight",
  "seed rot",
  "pre emergence damping off",
  "crown rot",
  "stem rot",
  "pink root",
  "basal rot",
  "virescence",
  "phyllody",
  "witches broom",
  "little leaf",
  "stunting",
  "yellowing",
  "chlorosis",
  "necrosis",
  "die back",
  "phytoplasma",
  "spiroplasma",
  "viroid",
  "begomovirus",
  "thrips tabaci",
  "frankiniella",
  "caliothrips",
  "scirtothrips",
  "tuta absoluta",
  "tomato leafminer",
  "south american leafminer",
  "pheromone trap",
  "yellow sticky trap",
  "blue sticky trap",
  "light trap",
  "blt",
  "pitfall trap",
  "delta trap",
  "funnel trap",
  "monitoring",
  "scouting",
  "etl",
  "economic threshold level",
  "pest forecasting",
  "disease forecasting",
  "weather based forecast",
  "bioagent",
  "trichogramma",
  "chrysoperla",
  "coccinella",
  "ladybird",
  "lacewing",
  "syrphid fly",
  "braconid",
  "parasitoid",
  "predator",
  "natural enemy",
  "augmentative release",
  "fumigation",
  "phosphine",
  "methyl bromide",
  "ecofumigation",
  "quarantine pest",
  "invasive species",
  "exotic pest",
  "spray schedule",
  "spray calendar",
  "dose per litre",
  "waiting period",
  "pre harvest interval",
  "phi",
  "residue",
  "pesticide residue",
  "mrls",

  // ── Weather & Climate ──────────────────────────────────────────────────────
  "monsoon",
  "rainfall",
  "rain",
  "heavy rain",
  "light rain",
  "flood",
  "flooding",
  "waterlogging",
  "water logging",
  "stagnant water",
  "cold",
  "frost",
  "frost damage",
  "hail",
  "hailstorm",
  "hail storm",
  "heat",
  "heat wave",
  "heat stress",
  "temperature",
  "high temperature",
  "humidity",
  "relative humidity",
  "wind",
  "wind damage",
  "storm",
  "climate",
  "climate change",
  "weather",
  "season",
  "kharif",
  "rabi",
  "zaid",
  "sowing",
  "sowing time",
  "sowing window",
  "delay sowing",
  "early sowing",
  // ── Additional Weather & Climate ─────────────────────────────────────────────
  "cyclone",
  "typhoon",
  "hurricane",
  "tornado",
  "thunderstorm",
  "lightning",
  "dry spell",
  "drought spell",
  "prolonged drought",
  "flash flood",
  "riverine flood",
  "coastal flood",
  "urban flood",
  "snow",
  "snowfall",
  "snowmelt",
  "ice",
  "ice storm",
  "sleet",
  "dew",
  "dew point",
  "fog",
  "dense fog",
  "smog",
  "mist",
  "cold wave",
  "cold snap",
  "cold day",
  "cold night",
  "warm spell",
  "warming trend",
  "el nino",
  "la nina",
  "iod",
  "indian ocean dipole",
  "enso",
  "mjo",
  "madden julian oscillation",
  "solar radiation",
  "sunshine hours",
  "photo period",
  "photoperiod",
  "short day plant",
  "long day plant",
  "neutral day plant",
  "growing degree days",
  "gdd",
  "heat unit",
  "base temperature",
  "crop calendar",
  "agrometeorological",
  "agromet",
  "agromet advisory",
  "weather forecast",
  "medium range forecast",
  "extended forecast",
  "imd",
  "india meteorological department",
  "automatic weather station",
  "aws",
  "rain gauge",
  "minimum thermometer",
  "maximum thermometer",
  "hygrometer",
  "anemometer",
  "pyranometer",
  "evaporation pan",
  "lysimeter",
  "climate smart agriculture",
  "climate resilience",
  "adaptation",
  "mitigation",
  "carbon sequestration",
  "greenhouse gas",
  "ghg",
  "co2 emission",
  "methane",
  "nitrous oxide",
  "carbon footprint",
  "low carbon farming",
  "sustainable agriculture",
  "sustainability",
  "pre monsoon",
  "onset of monsoon",
  "retreat of monsoon",
  "northeast monsoon",
  "southwest monsoon",
  "inter tropical convergence zone",
  "itcz",
  "low pressure area",
  "cyclonic circulation",
  "trough",

  // ── Farm Machinery & Mechanisation ─────────────────────────────────────────
  "tractor",
  "power tiller",
  "rotavator",
  "plough",
  "plow",
  "harrow",
  "cultivator",
  "seed drill",
  "seeder",
  "transplanter",
  "paddy transplanter",
  "mechanical transplanter",
  "reaper",
  "harvester",
  "combine harvester",
  "thresher",
  "threshing",
  "winnowing",
  "cleaning",
  "sprayer",
  "knapsack sprayer",
  "power sprayer",
  "duster",
  "fogger",
  "decorticator",
  "oil expeller",
  "flour mill",
  "grinder",
  // ── Additional Machinery ─────────────────────────────────────────────────────
  "mini tractor",
  "walk behind tractor",
  "two wheel tractor",
  "four wheel tractor",
  "hp",
  "horsepower",
  "pto",
  "power take off",
  "three point linkage",
  "hydraulic",
  "disc plough",
  "mould board plough",
  "chisel plough",
  "subsoiler",
  "deep ploughing",
  "zero tillage",
  "no till drill",
  "strip till",
  "minimum tillage",
  "conservation tillage",
  "reduced tillage",
  "disc harrow",
  "offset harrow",
  "spike tooth harrow",
  "spring tooth harrow",
  "leveler",
  "land leveler",
  "laser leveler",
  "blade harrow",
  "ridger",
  "furrower",
  "bed former",
  "raised bed planter",
  "broad bed furrow",
  "bbf",
  "permanent bed",
  "tied ridge",
  "ridge planting",
  "pneumatic seeder",
  "vacuum seeder",
  "drum seeder",
  "mat nursery",
  "dapog nursery",
  "wetbed nursery",
  "dry nursery",
  "mat nursery seedling",
  "rice transplanter",
  "vegetable transplanter",
  "onion transplanter",
  "sugarcane planter",
  "potato planter",
  "garlic planter",
  "zero till ferti seed drill",
  "happy seeder",
  "turbo seeder",
  "raised bed planter",
  "precision planter",
  "multi crop planter",
  "inter row cultivator",
  "weeder",
  "cono weeder",
  "rotary weeder",
  "power weeder",
  "wheel hoe",
  "reaper binder",
  "vertical conveyor reaper",
  "track harvester",
  "self propelled reaper",
  "walking type reaper",
  "axial flow thresher",
  "multi crop thresher",
  "maize sheller",
  "groundnut digger",
  "potato digger",
  "root vegetable harvester",
  "cotton picker",
  "sugarcane harvester",
  "baler",
  "hay baler",
  "straw baler",
  "round baler",
  "square baler",
  "chaff cutter",
  "fodder harvester",
  "green fodder chopper",
  "root cutter",
  "sugar beet harvester",
  "irrigation pump",
  "centrifugal pump",
  "jet pump",
  "gear pump",
  "hydraulic ram",
  "water wheel",
  "persian wheel",
  "rope and bucket",
  "boom sprayer",
  "tractor mounted sprayer",
  "self propelled sprayer",
  "helicopter spray",
  "drone spray",
  "aerial spray",
  "uav",
  "granule applicator",
  "soil applicator",
  "fumigant applicator",
  "precision agriculture",
  "gps",
  "gnss",
  "variable rate application",
  "vra",
  "remote sensing",
  "satellite imagery",
  "ndvi",
  "crop sensor",
  "yield monitor",
  "grain flow sensor",
  "auto steer",
  "guidance system",
  "section control",
  "cold press",
  "expeller",
  "oil extraction",
  "solvent extraction",
  "rice huller",
  "rice polisher",
  "satake",
  "whitener",
  "dal mill",
  "pulse mill",
  "grain cleaning machine",
  "grading machine",
  "colour sorter",
  "optical sorter",
  "weighbridge",
  "moisture meter",
  "grain moisture tester",
  "post harvest machinery",
  "food processing machine",
  "refrigerated van",
  "cold chain",
  "reefer vehicle",

  // ── Fertiliser Use & Availability ──────────────────────────────────────────
  "fertilizer",
  "fertiliser",
  "dose",
  "dose per acre",
  "dose per hectare",
  "npk ratio",
  "basal dose",
  "top dressing",
  "foliar spray",
  "foliar application",
  "broadcasting",
  "band placement",
  "spot placement",
  "fertigation",
  "slow release",
  "controlled release",
  "urea ammonium nitrate",
  "micronutrient mixture",
  "chelated micronutrient",
  "iron sulphate",
  "zinc sulphate",
  "borax",
  "urea prilled",
  "urea granular",
  "ssp",
  "single super phosphate",
  // ── Additional Fertiliser ────────────────────────────────────────────────────
  "mop",
  "muriate of potash",
  "sop",
  "sulphate of potash",
  "potassium chloride",
  "potassium nitrate",
  "potassium sulphate",
  "potassium magnesium sulphate",
  "calcium ammonium nitrate",
  "can",
  "ammonium sulphate",
  "ammonium nitrate",
  "calcium nitrate",
  "sodium nitrate",
  "Chilean nitrate",
  "tsp",
  "triple super phosphate",
  "rock phosphate",
  "bone meal",
  "blood meal",
  "fish meal fertilizer",
  "castor cake",
  "neem cake",
  "karanj cake",
  "groundnut cake",
  "mahua cake",
  "mustard cake",
  "cotton seed cake",
  "sunflower cake",
  "sesame cake",
  "peat",
  "cocopeat",
  "coir pith",
  "coir compost",
  "sugarcane press mud",
  "biogas slurry",
  "compost tea",
  "liquid manure",
  "calcium boron",
  "calcium magnesium",
  "magnesium sulphate",
  "ferrous sulphate",
  "zinc edta",
  "iron edta",
  "manganese sulphate",
  "copper sulphate",
  "sodium molybdate",
  "boric acid",
  "humic acid fertilizer",
  "seaweed fertilizer",
  "seaweed powder",
  "amino acid fertilizer",
  "protein hydrolysate",
  "nano fertilizer",
  "nano urea",
  "nano dap",
  "nano zinc",
  "crop specific fertilizer",
  "specialty fertilizer",
  "soil application",
  "soil incorporation",
  "sub surface placement",
  "side dressing",
  "starter dose",
  "split dose",
  "single dose",
  "in furrow application",
  "seed furrow",
  "row application",
  "fertigation dose",
  "drip fertilizer",
  "water soluble npk",
  "soil test based fertilizer",
  "soil health card recommendation",
  "nutrient management",
  "balanced nutrition",
  "integrated nutrient management",
  "inm",
  "integrated soil fertility management",
  "isfm",

  // ── Harvest & Post-Harvest ──────────────────────────────────────────────────
  "harvest",
  "harvesting",
  "harvest time",
  "maturity",
  "maturity index",
  "harvesting stage",
  "optimum harvest",
  "timely harvest",
  "delayed harvest",
  "yield",
  "yield estimate",
  "expected yield",
  "low yield",
  "yield loss",
  "grain",
  "grain moisture",
  "drying",
  "sun drying",
  "mechanical drying",
  "storage",
  "godown",
  "warehouse",
  "cold storage",
  "crushing",
  "processing",
  "value addition",
  "grading",
  "sorting",
  "packaging",
  "milling",
  "rice milling",
  "sugarcane crushing",
  // ── Additional Post-Harvest ──────────────────────────────────────────────────
  "physiological maturity",
  "harvest maturity",
  "commercial maturity",
  "refractometer",
  "brix",
  "firmness",
  "colour index",
  "starch iodine test",
  "cutting test",
  "oil content test",
  "protein test",
  "threshing loss",
  "harvesting loss",
  "field loss",
  "transport loss",
  "storage loss",
  "post harvest loss",
  "food loss",
  "food waste",
  "on farm storage",
  "hermetic storage",
  "hermetic bag",
  "super grain bag",
  "metal silo",
  "mud bin",
  "bamboo bin",
  "metal drum",
  "sealed storage",
  "pusa bin",
  "hapur bin",
  "kothi",
  "coal tar treatment",
  "grain protectant",
  "malathion dust",
  "phostoxin",
  "aluminium phosphide",
  "edible coating",
  "wax coating",
  "fruit coating",
  "shrink wrap",
  "modified atmosphere",
  "ma storage",
  "controlled atmosphere",
  "ca storage",
  "ethylene absorber",
  "ethylene scrubber",
  "potassium permanganate sachet",
  "curing",
  "potato curing",
  "onion curing",
  "garlic curing",
  "yam curing",
  "sweet potato curing",
  "ripening",
  "ethylene ripening",
  "carbide ripening",
  "degreening",
  "irradiation",
  "gamma irradiation",
  "x ray irradiation",
  "food irradiation",
  "hot water treatment",
  "vapor heat treatment",
  "vht",
  "heat treatment",
  "hydro cooling",
  "forced air cooling",
  "vacuum cooling",
  "ice cooling",
  "pre cooling",
  "field heat removal",
  "evaporative cooling",
  "evaporative cool chamber",
  "zero energy cool chamber",
  "zecc",
  "refrigeration",
  "refrigerator",
  "cool room",
  "blast freezer",
  "quick freeze",
  "iqf",
  "individual quick freeze",
  "dehydration",
  "drying",
  "spray drying",
  "drum drying",
  "tray drying",
  "cabinet dryer",
  "solar dryer",
  "tunnel dryer",
  "fluidized bed dryer",
  "freeze drying",
  "lyophilization",
  "osmotic dehydration",
  "canning",
  "retort",
  "autoclave",
  "thermal processing",
  "pasteurization",
  "blanching",
  "hot break",
  "cold break",
  "aseptic processing",
  "bottling",
  "tetra pak",
  "pouch packaging",
  "flexible packaging",
  "map",
  "modified atmosphere packaging",
  "vacuum pack",
  "jam",
  "jelly",
  "marmalade",
  "pickle",
  "chutney",
  "sauce",
  "ketchup",
  "squash",
  "juice",
  "nectar",
  "syrup",
  "candy",
  "murabba",
  "chips",
  "wafer",
  "snack",
  "flour",
  "starch",
  "glucose",
  "maltodextrin",
  "oil extraction",
  "mustard oil",
  "groundnut oil",
  "coconut oil",
  "palm oil",
  "soybean oil",
  "sunflower oil",
  "sesame oil",
  "castor oil",
  "bio diesel",
  "bio fuel",
  "ethanol",
  "bio ethanol",
  "bio gas",
  "fodder processing",
  "hay making",
  "silage making",
  "urea treated straw",
  "total mixed ration",
  "complete feed block",
  "wool processing",
  "wool grading",
  "wool scouring",
  "honey extraction",
  "honey processing",
  "beeswax",
  "fish drying",
  "fish smoking",
  "fish canning",
  "surimi",
  "prawn peeling",
  "shrimp processing",
  "milk processing",
  "pasteurised milk",
  "uht milk",
  "skimmed milk",
  "condensed milk",
  "milk powder",
  "whey powder",
  "paneer",
  "khoa",
  "food safety",
  "fssai",
  "haccp",
  "good manufacturing practice",
  "gmp",
  "iso 22000",
  "agmark",
  "bis",
  "codex alimentarius",

  // ── Government Schemes & Credit ─────────────────────────────────────────────
  "pm kisan",
  "pmkisan",
  "fasal bima",
  "crop insurance",
  "crop loan",
  "kisan credit",
  "kisan credit card",
  "kcc",
  "subsidy",
  "subsidies",
  "pmfby",
  "restructured crop loan",
  "interest subsidy",
  "minimum support price",
  "msp",
  "procurement",
  "mandi",
  "mandi price",
  // ── Additional Schemes & Policy ───────────────────────────────────────────
  "rashtriya krishi vikas yojana",
  "rkvy",
  "national food security mission",
  "nfsm",
  "national horticulture mission",
  "nhm",
  "nmoop",
  "nmsa",
  "national mission sustainable agriculture",
  "midh",
  "mission for integrated development of horticulture",
  "paramparagat krishi vikas yojana",
  "pkvy",
  "soil health management",
  "shm",
  "sub mission agricultural mechanization",
  "smam",
  "sub mission seeds and planting material",
  "smsp",
  "national bamboo mission",
  "nbm",
  "nmhs",
  "national mission honey bee",
  "pradhan mantri fasal bima yojana",
  "pmfby",
  "restructured weather based crop insurance",
  "rwbcis",
  "per drop more crop",
  "micro irrigation fund",
  "e nam",
  "national agriculture market",
  "e-nam",
  "agri infra fund",
  "agriculture infrastructure fund",
  "aif",
  "atal bhujal yojana",
  "pradhan mantri krishi sinchai yojana",
  "pmksy",
  "har khet ko pani",
  "more crop per drop",
  "gramin bhandaran yojana",
  "warehouse receipt",
  "negotiable warehouse receipt",
  "nwr",
  "electronic nwr",
  "enwr",
  "wdra",
  "kisaan rail",
  "krishi udaan",
  "kisan drone",
  "digital agriculture",
  "agristack",
  "farmer registry",
  "land records",
  "soil health card",
  "shc",
  "nutrient based subsidy",
  "nbs",
  "new urea policy",
  "dbt",
  "direct benefit transfer",
  "pm kisan maandhan",
  "pension scheme",
  "social security",
  "kisaan samman nidhi",
  "income support",
  "farmer income",
  "pm formalisation of micro food enterprises",
  "fme",
  "odop",
  "one district one product",
  "aatmanirbhar bharat",
  "contract farming",
  "farmer producer organisation",
  "fpo",
  "farmer cooperative",
  "primary agricultural credit society",
  "pacs",
  "nafed",
  "sfac",
  "ncdc",
  "nddb",
  "nabard",
  "rkcc",
  "agri loan",
  "agricultural finance",
  "rural credit",
  "cooperative bank",
  "land development bank",
  "regional rural bank",
  "rrb",
  "commercial bank agriculture",
  "priority sector lending",
  "psl",
  "agriculture credit target",
  "crop loan interest subvention",
  "interest subvention scheme",
  "input subsidy",
  "seed subsidy",
  "fertilizer subsidy",
  "machinery subsidy",
  "irrigation subsidy",
  "drip subsidy",
  "electricity subsidy",
  "pump subsidy",
  "cold storage subsidy",
  "food corporation of india",
  "fci",
  "state procurement agency",
  "central pool",
  "price support scheme",
  "pss",
  "market intervention scheme",
  "mis",
  "price stabilisation fund",
  "agri export",
  "agri export zone",
  "aez",
  "agricultural export policy",
  "apeda",
  "mpeda",
  "export promotion",
  "geoindication",
  "gi tag",

  // ── Seed & Variety ──────────────────────────────────────────────────────────
  "seed",
  "seeds",
  "variety",
  "varieties",
  "high yield",
  "high yielding",
  "hyv",
  "hybrid",
  "op",
  "open pollinated",
  "improved variety",
  "variety selection",
  "seed rate",
  "seed treatment",
  "seed coating",
  "seed priming",
  "germination",
  "germination test",
  "seed quality",
  "foundation seed",
  "certified seed",
  "truthful label seed",
  "tl seed",
  // ── Additional Seed & Variety ────────────────────────────────────────────────
  "nucleus seed",
  "breeder seed",
  "registered seed",
  "pre basic seed",
  "seed production",
  "seed village",
  "seed hub",
  "seed bank",
  "community seed bank",
  "traditional variety",
  "local variety",
  "landrace",
  "heirloom",
  "heritage variety",
  "folk variety",
  "drought tolerant variety",
  "flood tolerant variety",
  "heat tolerant variety",
  "salt tolerant variety",
  "submergence tolerant",
  "swarna sub1",
  "semi dwarf",
  "tall variety",
  "dwarf",
  "semi dwarf wheat",
  "short duration",
  "medium duration",
  "long duration",
  "determinate",
  "indeterminate",
  "semi determinate",
  "photoperiod sensitive",
  "photoperiod insensitive",
  "gmo",
  "genetically modified organism",
  "bt cotton",
  "bt brinjal",
  "gm crop",
  "transgenic",
  "biofortified",
  "golden rice",
  "qpm",
  "quality protein maize",
  "dha rice",
  "protein rich",
  "provitamin a",
  "iron rich",
  "zinc rich variety",
  "marker assisted selection",
  "mas",
  "qtl",
  "genomic selection",
  "gene editing",
  "crispr",
  "cas9",
  "cisgenics",
  "plant variety protection",
  "pvp",
  "ppvfra",
  "plant breeders right",
  "ipr",
  "intellectual property right",
  "patent",
  "seed certification",
  "seed act",
  "seed policy",
  "icar",
  "state agricultural university",
  "sau",
  "krishi vigyan kendra",
  "kvk",
  "seed company",
  "private sector seed",
  "public sector seed",
  "seed import",
  "seed export",
  "quarantine",
  "phytosanitary",
  "seed viability",
  "seed longevity",
  "seed storage",
  "seed moisture content",
  "seed treatment chemical",
  "thiram",
  "captan",
  "metalaxyl",
  "carbendazim seed treatment",
  "imidacloprid seed treatment",
  "bio seed treatment",
  "trichoderma seed treatment",
  "rhizobium inoculant",
  "seed pelleting",
  "seed encrusting",
  "film coating",
  "hydropriming",
  "halo priming",
  "osmopriming",
  "solid matrix priming",
  "matriconditioning",
  "hot water seed treatment",
  "grow out test",
  "dna fingerprinting",
  "variety identification",
  "seed multiplication",
  "seed plot",
  "isolation distance",
  "detasseling",
  "male sterility",
  "cms",
  "cytoplasmic male sterility",
  "self incompatibility",

  // ── General Agricultural Terms ─────────────────────────────────────────────
  "crop",
  "crops",
  "farming",
  "agriculture",
  "agricultural",
  "agronomy",
  "agronomic",
  "horticulture",
  "vegetable cultivation",
  "fruit cultivation",
  "fruit",
  "fruits",
  "grow",
  "growing",
  "cultivation",
  "field",
  "field crop",
  "plantation",
  "orchard",
  "garden",
  "plant",
  "plants",
  "transplanting",
  "intercrop",
  "intercropping",
  "mixed cropping",
  "relay cropping",
  "sequence cropping",
  "crop rotation",
  "crop residue",
  "stubble",
  "stubble burning",
  "weeding",
  "weed control",
  "weed management",
  "herbicide spray",
  "pruning",
  "training",
  "canopy management",
  "pinching",
  "desuckering",
  "grafting",
  "budding",
  "layering",
  "propagation",
  "hardening off",
  "biomass",
  "crop waste",
  "straw management",
  // ── Additional General Terms ─────────────────────────────────────────────────
  "crop husbandry",
  "crop management",
  "crop production",
  "crop science",
  "crop physiology",
  "crop ecology",
  "crop modelling",
  "cropping system",
  "farming system",
  "integrated farming",
  "ifm",
  "ifms",
  "integrated farming system",
  "composite farming",
  "subsistence farming",
  "commercial farming",
  "smallholder farming",
  "smallholder",
  "marginal farmer",
  "small farmer",
  "large farmer",
  "tenant farmer",
  "sharecropper",
  "landless farmer",
  "farm labourer",
  "farm worker",
  "agricultural labourer",
  "casual labour",
  "farm income",
  "farm profit",
  "cost of cultivation",
  "cost of production",
  "input cost",
  "labour cost",
  "returns",
  "net return",
  "bcr",
  "benefit cost ratio",
  "break even",
  "profitability",
  "land holding",
  "land size",
  "plot",
  "survey number",
  "khasra",
  "land use",
  "land utilization",
  "cropping intensity",
  "net sown area",
  "gross cropped area",
  "fallow land",
  "cultivated land",
  "uncultivated",
  "wasteland",
  "degraded land",
  "reclaimed land",
  "land reform",
  "land consolidation",
  "land fragmentation",
  "farm management",
  "record keeping",
  "farm diary",
  "farm account",
  "farm plan",
  "enterprise selection",
  "crop planning",
  "village",
  "taluk",
  "block",
  "district",
  "state",
  "krishi",
  "cultivator",
  "grower",
  "producer",
  "farmer",
  "kisaan",
  "kisan",
  "extension",
  "extension worker",
  "agricultural extension",
  "ati",
  "agricultural training institute",
  "atma",
  "agriculture technology management agency",
  "kisan call centre",
  "1551",
  "helpline",
  "field demonstration",
  "front line demonstration",
  "fld",
  "technology transfer",
  "knowledge transfer",
  "training",
  "exposure visit",
  "farm school",
  "farmer field school",
  "ffs",
  "self help group",
  "shg",
  "women farmer",
  "women in agriculture",
  "youth in agriculture",
  "farm youth",
  "agri entrepreneur",
  "agribusiness",
  "agro industry",
  "value chain",
  "supply chain",
  "market linkage",
  "buyer seller meet",
  "farmer market",
  "haat bazaar",
  "apmc",
  "agriculture produce market committee",
  "regulated market",
  "farmer producer company",
  "collective marketing",
  "organic certification",
  "pgS",
  "participatory guarantee system",
  "fair trade",
  "fair price",
  "price discovery",
  "market intelligence",
  "commodity exchange",
  "futures market",
  "spot market",
  "forward contract",
  "hedging",
  "price risk management",
  "agroforestry",
  "silvopasture",
  "silvoarable",
  "home garden",
  "kitchen garden",
  "nutritional garden",
  "multi strata garden",
  "terrace farming",
  "hill agriculture",
  "tribal farming",
  "coastal agriculture",
  "delta farming",
  "flood plain farming",
  "rainfed farming",
  "dryland farming",
  "dry land",
  "dryland",
  "watershed approach",
  "integrated watershed",
  "natural resource management",

  // ── Plant Growth Regulators ─────────────────────────────────────────────────
  "ga3",
  "gibberellin",
  "cytokinin",
  "ethylene",
  "iba",
  "naa",
  "planofix",
  "maleic hydrazide",
  "paclobutrazol",
  "ccc",
  "ethephon",
  // ── Additional PGR & Physiology ──────────────────────────────────────────────
  "auxin",
  "indole acetic acid",
  "iaa",
  "indole butyric acid",
  "naphthalene acetic acid",
  "synthetic auxin",
  "rooting hormone",
  "zeatin",
  "kinetin",
  "benzyladenine",
  "ba",
  "6 bap",
  "thidiazuron",
  "tdz",
  "abscisic acid",
  "aba",
  "jasmonic acid",
  "salicylic acid",
  "brassinosteroid",
  "polyamine",
  "putrescine",
  "spermidine",
  "triacontanol",
  "nitrophenol",
  "growth retardant",
  "growth promoter",
  "growth inhibitor",
  "cell division",
  "cell elongation",
  "differentiation",
  "apical dominance",
  "lateral bud break",
  "branching",
  "stem elongation",
  "internode elongation",
  "dwarfing",
  "vernalization",
  "stratification",
  "cold requirement",
  "chilling requirement",
  "chilling hours",
  "dormancy breaking",
  "hydrogen cyanamide",
  "rest breaking agent",
  "thiorea",
  "sprouting agent",
  "thinning",
  "fruit thinning",
  "chemical thinning",
  "manual thinning",
  "naphthalene acetic amide",
  "naa amide",
  "carbaryl",
  "benzyladenine thinning",
  "return bloom",
  "biennial bearing",
  "alternate bearing",
  "color development",
  "anthocyanin",
  "red coloration",
  "degreening",
  "ripening promoter",
  "ripening inhibitor",
  "1 mcp",
  "1 methylcyclopropene",
  "smartfresh",
  "ethylbloc",
  "tissue culture",
  "micropropagation",
  "in vitro",
  "explant",
  "callus",
  "somatic embryogenesis",
  "organogenesis",
  "ms medium",
  "murashige skoog",
  "hormone ratio",
  "auxin cytokinin ratio",
  "shoot multiplication",
  "rooting medium",
  "acclimatization",
  "hardening",
  "nursery hardening",
  "shade net hardening",

  // ── Pollination & Fruit Set ─────────────────────────────────────────────────
  "pollination",
  "bee pollination",
  "honey bee",
  "beekeeping",
  "apiary",
  "fruit set",
  "fruit drop",
  "flower drop",
  "blossom drop",
  "parthenocarpy",
  // ── Additional Pollination & Ecology ─────────────────────────────────────────
  "cross pollination",
  "self pollination",
  "open pollination",
  "wind pollination",
  "anemophily",
  "insect pollination",
  "entomophily",
  "pollinizer",
  "pollinator",
  "compatible variety",
  "incompatible",
  "pollen viability",
  "pollen germination",
  "pollen tube",
  "stigma receptivity",
  "style",
  "ovary",
  "fertilization",
  "double fertilization",
  "embryo sac",
  "endosperm",
  "fruit development",
  "fruit growth",
  "cell division phase",
  "cell expansion phase",
  "maturation phase",
  "bumble bee",
  "solitary bee",
  "mason bee",
  "stingless bee",
  "meliponiculture",
  "butterfly",
  "moth",
  "hoverfly",
  "beetle pollinator",
  "bat pollination",
  "chiropterophily",
  "bird pollination",
  "ornithophily",
  "water pollination",
  "hydrophily",
  "colony collapse disorder",
  "ccd",
  "varroa mite",
  "varroa destructor",
  "nosema",
  "american foul brood",
  "european foul brood",
  "hive management",
  "colony management",
  "queen rearing",
  "queen bee",
  "worker bee",
  "drone bee",
  "bee colony",
  "bee colony strength",
  "honey flow",
  "dearth period",
  "feeding bees",
  "sugar syrup feeding",
  "royal jelly",
  "bee pollen",
  "propolis",
  "bee venom",
  "apitherapy",
  "flower colour",
  "flower fragrance",
  "nectary",
  "nectar",
  "pollen",

  // ── Organic & Natural Farming ────────────────────────────────────────────────
  "subhash palekar",
  "zbnf",
  "zero budget natural farming",
  "natural inputs",
  "jeevanmrit",
  "sasyamrit",
  "panchakavya",
  "dashparni",
  "neemastra",
  "agnihotra",
  "homa farming",
  "biodynamic farming",
  "biodynamic",
  "demeter",
  "steiner",
  "permaculture",
  "food forest",
  "guild planting",
  "companion planting",
  "allelopathy",
  "allelopathic",
  "trap crop",
  "push pull",
  "cover crop",
  "living mulch",
  "smother crop",
  "organic manure",
  "organic input",
  "organic matter",
  "soil biology",
  "soil food web",
  "mycorrhizal network",
  "regenerative agriculture",
  "regenerative farming",
  "holistic management",
  "adaptive multi paddock",
  "amp grazing",
  "carbon farming",
  "carbon credit",
  "voluntary carbon market",
  "soil carbon",
  "humus building",
  "organic matter building",

  // ── Agricultural Economics & Marketing ──────────────────────────────────────
  "market price",
  "wholesale price",
  "retail price",
  "farm gate price",
  "spot price",
  "auction price",
  "tender price",
  "commodity",
  "commodity market",
  "agri commodity",
  "buyer",
  "seller",
  "trader",
  "commission agent",
  "aratiya",
  "dalal",
  "broker",
  "aggregator",
  "processor",
  "retailer",
  "consumer",
  "direct marketing",
  "direct selling",
  "farmer to consumer",
  "contract farming",
  "buyback arrangement",
  "assured market",
  "price support",
  "floor price",
  "procurement price",
  "fair price",
  "market surplus",
  "marketable surplus",
  "marketed surplus",
  "transport",
  "transportation",
  "freight",
  "logistics",
  "cold chain logistics",
  "last mile",
  "first mile",
  "aggregation centre",
  "collection centre",
  "grading centre",
  "pack house",
  "export",
  "import",
  "trade",
  "tariff",
  "non tariff barrier",
  "sanitary and phytosanitary",
  "sps",
  "tbt",
  "technical barrier to trade",
  "agri export",
  "agri import",
  "balance of trade",

  // ── Technology & Digital Agriculture ─────────────────────────────────────────
  "artificial intelligence",
  "machine learning",
  "deep learning",
  "ai in agriculture",
  "iot",
  "internet of things",
  "smart farming",
  "precision farming",
  "big data",
  "data analytics",
  "farm data",
  "sensor data",
  "drone",
  "unmanned aerial vehicle",
  "uav",
  "multispectral",
  "hyperspectral",
  "satellite",
  "remote sensing satellite",
  "sentinel",
  "landsat",
  "resourcesat",
  "ndvi",
  "ndwi",
  "evi",
  "lai",
  "vegetation index",
  "crop health monitoring",
  "yield prediction",
  "yield forecasting",
  "crop area estimation",
  "digital soil map",
  "soil nutrient map",
  "ec mapping",
  "gis",
  "geographic information system",
  "spatial analysis",
  "mobile app",
  "agri app",
  "farmer app",
  "crop advisory app",
  "chatbot",
  "voice bot",
  "ivr",
  "sms advisory",
  "e commerce",
  "online market",
  "agri portal",
  "digital platform",
  "block chain",
  "supply chain traceability",
  "qr code",
  "bar code",
  "rfid",
  "track and trace",
  "weather app",
  "weather api",
  "weather data",
  "microclimate",
  "crop simulation model",
  "dssat",
  "oryza",
  "cropwat",

  // ── Environment & Sustainability ──────────────────────────────────────────────
  "biodiversity",
  "agro biodiversity",
  "genetic diversity",
  "genetic resource",
  "plant genetic resource",
  "gene bank",
  "national gene bank",
  "nbpgr",
  "wild relative",
  "wild crop relative",
  "conservation",
  "ecosystem service",
  "pollination service",
  "natural pest control",
  "nutrient cycling",
  "water purification",
  "flood regulation",
  "carbon stock",
  "above ground biomass",
  "below ground biomass",
  "deforestation",
  "afforestation",
  "reforestation",
  "tree plantation",
  "social forestry",
  "farm forestry",
  "van mahotsav",
  "wetland",
  "mangrove",
  "estuary",
  "backwater",
  "paddy field ecology",
  "migratory bird",
  "bird in farmland",
  "farmland bird",
  "barn owl",
  "pesticide pollution",
  "water pollution",
  "soil pollution",
  "air pollution",
  "heavy metal",
  "cadmium",
  "lead",
  "arsenic",
  "mercury",
  "chromium",
  "soil remediation",
  "phytoremediation",
  "bioremediation",
  "integrated solid waste management",
  "crop residue management",
  "stubble management",
  "happy seeder",
  "turbo happy seeder",
  "in situ decomposition",
  "ex situ use",
  "biomass power",
  "renewable energy",
  "solar energy",
  "wind energy",
  "biogas energy",
  "solar panel farm",
  "agrivoltaics",
  "agri solar",
  "dual use",
]);

/**
 * Stop-words — non-agricultural noise terms that appear in casual Hindi/English
 * sentences but should not contribute to the agriculture score.
 */
const STOP_WORDS = new Set([
  // ── English: Articles & Determiners ────────────────────────────────────────
  "the",
  "a",
  "an",
  "this",
  "that",
  "these",
  "those",
  "every",
  "each",
  "either",
  "neither",
  "both",
  "all",
  "any",
  "some",
  "few",
  "many",
  "much",
  "more",
  "most",
  "less",
  "least",
  "other",
  "another",
  "such",
  "own",
  "same",
  "no",
  "enough",
  "several",
  "certain",
  "whole",
  "half",

  // ── English: Pronouns ───────────────────────────────────────────────────────
  "i",
  "me",
  "my",
  "mine",
  "myself",
  "we",
  "us",
  "our",
  "ours",
  "ourselves",
  "you",
  "your",
  "yours",
  "yourself",
  "yourselves",
  "he",
  "him",
  "his",
  "himself",
  "she",
  "her",
  "hers",
  "herself",
  "it",
  "its",
  "itself",
  "they",
  "them",
  "their",
  "theirs",
  "themselves",
  "what",
  "which",
  "who",
  "whom",
  "whose",
  "one",
  "ones",
  "anyone",
  "anyone",
  "everyone",
  "no one",
  "nobody",
  "somebody",
  "something",
  "anything",
  "everything",
  "nothing",
  "wherever",
  "whoever",
  "whomever",
  "whatever",
  "whichever",

  // ── English: Auxiliary & Modal Verbs ───────────────────────────────────────
  "am",
  "is",
  "are",
  "was",
  "were",
  "be",
  "been",
  "being",
  "have",
  "has",
  "had",
  "having",
  "do",
  "does",
  "did",
  "done",
  "doing",
  "will",
  "would",
  "shall",
  "should",
  "can",
  "could",
  "may",
  "might",
  "must",
  "need",
  "dare",
  "ought",
  "used",
  "get",
  "got",
  "gotten",
  "getting",
  "let",
  "lets",
  "make",
  "makes",
  "made",
  "go",
  "goes",
  "went",
  "come",
  "comes",
  "came",
  "say",
  "said",
  "says",
  "tell",
  "told",
  "tells",
  "know",
  "knew",
  "knows",
  "think",
  "thought",
  "thinks",
  "see",
  "saw",
  "seen",
  "look",
  "looked",
  "looks",
  "want",
  "wanted",
  "wants",
  "like",
  "liked",
  "likes",

  // ── English: Prepositions ───────────────────────────────────────────────────
  "to",
  "of",
  "in",
  "for",
  "on",
  "with",
  "at",
  "by",
  "from",
  "as",
  "into",
  "through",
  "during",
  "before",
  "after",
  "above",
  "below",
  "between",
  "under",
  "over",
  "up",
  "down",
  "out",
  "off",
  "about",
  "against",
  "along",
  "among",
  "around",
  "behind",
  "beside",
  "besides",
  "beyond",
  "except",
  "inside",
  "near",
  "outside",
  "per",
  "regarding",
  "since",
  "throughout",
  "toward",
  "towards",
  "upon",
  "within",
  "without",
  "across",
  "beneath",
  "concerning",
  "considering",
  "despite",
  "following",
  "including",
  "onto",
  "opposite",
  "past",
  "plus",
  "round",
  "unlike",
  "until",
  "unto",
  "versus",
  "via",
  "amongst",
  "amid",
  "amidst",

  // ── English: Conjunctions ───────────────────────────────────────────────────
  "and",
  "but",
  "or",
  "nor",
  "yet",
  "so",
  "for",
  "if",
  "because",
  "although",
  "though",
  "even though",
  "while",
  "whereas",
  "whether",
  "unless",
  "until",
  "once",
  "since",
  "when",
  "whenever",
  "where",
  "wherever",
  "after",
  "before",
  "as",
  "than",
  "however",
  "therefore",
  "thus",
  "hence",
  "consequently",
  "accordingly",
  "moreover",
  "furthermore",
  "besides",
  "nevertheless",
  "nonetheless",
  "otherwise",
  "instead",
  "meanwhile",
  "also",
  "too",
  "either",
  "neither",
  "both",
  "not only",
  "but also",
  "rather",
  "although",

  // ── English: Adverbs ────────────────────────────────────────────────────────
  "again",
  "further",
  "then",
  "once",
  "here",
  "there",
  "when",
  "where",
  "why",
  "how",
  "not",
  "only",
  "just",
  "also",
  "very",
  "too",
  "so",
  "quite",
  "rather",
  "well",
  "now",
  "still",
  "even",
  "already",
  "always",
  "never",
  "often",
  "sometimes",
  "usually",
  "generally",
  "perhaps",
  "maybe",
  "probably",
  "certainly",
  "definitely",
  "really",
  "actually",
  "basically",
  "simply",
  "nearly",
  "almost",
  "ever",
  "yet",
  "soon",
  "later",
  "early",
  "late",
  "often",
  "away",
  "back",
  "together",
  "apart",
  "ahead",
  "instead",
  "else",
  "otherwise",
  "anyway",
  "thus",
  "hence",
  "therefore",
  "hence",
  "thereby",
  "therein",
  "thereof",
  "thereon",
  "therewith",
  "hereby",
  "herein",
  "hereof",
  "hereon",
  "herewith",
  "hereafter",

  // ── English: Question Words ─────────────────────────────────────────────────
  "what",
  "which",
  "who",
  "whom",
  "whose",
  "when",
  "where",
  "why",
  "how",
  "how much",
  "how many",
  "how long",
  "how far",
  "how often",
  "how soon",

  // ── English: Numbers & Quantifiers ─────────────────────────────────────────
  "one",
  "two",
  "three",
  "four",
  "five",
  "six",
  "seven",
  "eight",
  "nine",
  "ten",
  "first",
  "second",
  "third",
  "last",
  "next",
  "previous",
  "zero",
  "hundred",
  "thousand",
  "million",
  "billion",

  // ── English: Misc Common Words ──────────────────────────────────────────────
  "ok",
  "okay",
  "yes",
  "no",
  "yeah",
  "nope",
  "please",
  "thanks",
  "thank",
  "thank you",
  "hello",
  "hi",
  "hey",
  "bye",
  "goodbye",
  "sir",
  "madam",
  "mr",
  "mrs",
  "ms",
  "dr",
  "etc",
  "eg",
  "ie",
  "vs",
  "etc.",
  "new",
  "old",
  "good",
  "bad",
  "big",
  "small",
  "large",
  "little",
  "long",
  "short",
  "high",
  "low",
  "right",
  "left",
  "true",
  "false",
  "open",
  "close",
  "closed",
  "start",
  "end",
  "begin",
  "stop",
  "give",
  "take",
  "put",
  "set",
  "show",
  "find",
  "help",
  "need",
  "use",
  "using",
  "used",
  "uses",
  "try",
  "tried",
  "trying",
  "day",
  "days",
  "week",
  "weeks",
  "month",
  "months",
  "year",
  "years",
  "time",
  "times",
  "today",
  "yesterday",
  "tomorrow",
  "now",
  "then",
  "part",
  "parts",
  "place",
  "places",
  "thing",
  "things",
  "way",
  "ways",
  "number",
  "numbers",
  "name",
  "names",
  "type",
  "types",
  "kind",
  "kinds",
  "area",
  "areas",
  "lot",
  "lots",
  "point",
  "points",
  "case",
  "cases",
  "problem",
  "problems",
  "issue",
  "issues",
  "question",
  "questions",
  "information",
  "detail",
  "details",
  "example",
  "examples",
  "following",
  "above",
  "below",
  "here",
  "there",
  "where",
  "according",
  "based",
  "using",
  "including",
  "regarding",
  "related",
  "available",
  "possible",
  "different",
  "similar",
  "same",
  "various",

  // ── Hindi / Urdu (Roman Script) — Pronouns & Demonstratives ────────────────
  "main",
  "mai",
  "mujhe",
  "mujhko",
  "mera",
  "meri",
  "mere",
  "hum",
  "humein",
  "hamara",
  "hamari",
  "hamare",
  "aap",
  "aapko",
  "aapki",
  "aapke",
  "aapka",
  "apna",
  "apni",
  "apne",
  "tum",
  "tumhe",
  "tumhein",
  "tumhara",
  "tumhari",
  "tumare",
  "tu",
  "tujhe",
  "tera",
  "teri",
  "tere",
  "woh",
  "wo",
  "usse",
  "use",
  "usko",
  "uska",
  "uski",
  "uske",
  "unhe",
  "unhein",
  "unka",
  "unki",
  "unke",
  "yeh",
  "ye",
  "ise",
  "isko",
  "iska",
  "iski",
  "iske",
  "inhe",
  "inhein",
  "inka",
  "inki",
  "inke",
  "yahan",
  "wahan",
  "idhar",
  "udhar",
  "kahan",
  "kahin",
  "kahin",
  "koi",
  "kuch",
  "sab",
  "sabhi",
  "har",
  "dono",

  // ── Hindi / Urdu — Verbs ────────────────────────────────────────────────────
  "hai",
  "hain",
  "hoga",
  "honge",
  "hogi",
  "ho",
  "hua",
  "hui",
  "hue",
  "tha",
  "thi",
  "the",
  "rahega",
  "rahegi",
  "rahenge",
  "kar",
  "karo",
  "karo",
  "karna",
  "karni",
  "karne",
  "karta",
  "karti",
  "karte",
  "kiya",
  "kiye",
  "ki",
  "karein",
  "kijiye",
  "kariye",
  "hua",
  "hui",
  "hue",
  "hona",
  "honi",
  "hone",
  "dena",
  "dene",
  "deni",
  "diya",
  "diye",
  "di",
  "do",
  "dijiye",
  "lena",
  "lene",
  "leni",
  "liya",
  "liye",
  "li",
  "lo",
  "lijiye",
  "aana",
  "aane",
  "aani",
  "aaya",
  "aayi",
  "aaye",
  "ao",
  "aaiye",
  "jaana",
  "jaane",
  "jaani",
  "gaya",
  "gayi",
  "gaye",
  "jao",
  "jaiye",
  "rehna",
  "rehne",
  "rehni",
  "raha",
  "rahi",
  "rahe",
  "sakna",
  "sakta",
  "sakti",
  "sakte",
  "sake",
  "chahiye",
  "chahte",
  "chahti",
  "chahta",
  "chahna",
  "milna",
  "mila",
  "mile",
  "mili",
  "milta",
  "milti",
  "milte",
  "batana",
  "batao",
  "bataye",
  "bata",
  "batata",
  "batati",
  "batate",
  "dekhna",
  "dekho",
  "dekhe",
  "dekha",
  "dekhta",
  "dekhti",
  "dekhte",
  "sunna",
  "suno",
  "sune",
  "suna",
  "sunta",
  "sunti",
  "sunte",
  "samajhna",
  "samjho",
  "samjhe",
  "samjha",
  "samajhta",
  "samajhti",
  "samajhte",
  "poochna",
  "poocho",
  "poocha",
  "poochte",
  "poochti",
  "padhna",
  "padho",
  "padha",
  "padhte",
  "padhti",
  "likhna",
  "likho",
  "likha",
  "likhte",
  "likhti",

  // ── Hindi / Urdu — Postpositions & Particles ────────────────────────────────
  "ka",
  "ki",
  "ke",
  "kaa",
  "kee",
  "ko",
  "se",
  "mein",
  "par",
  "tak",
  "ke liye",
  "ke saath",
  "ke baad",
  "ke pehle",
  "ke upar",
  "ke neeche",
  "ke andar",
  "ke bahar",
  "ke paas",
  "ke bina",
  "ne",
  "bhi",
  "hi",
  "to",
  "toh",
  "na",
  "nahi",
  "nhi",
  "mat",
  "bilkul",
  "sirf",
  "bas",
  "phir",

  // ── Hindi / Urdu — Conjunctions & Discourse ────────────────────────────────
  "aur",
  "ya",
  "lekin",
  "magar",
  "par",
  "balki",
  "kyunki",
  "isliye",
  "kyun",
  "kyon",
  "toh",
  "tab",
  "jab",
  "jab bhi",
  "jabhi",
  "agar",
  "yadi",
  "to",
  "warna",
  "varna",
  "phir bhi",
  "toh bhi",
  "waise",
  "vaise",
  "matlab",
  "yani",
  "yaani",
  "aisa",
  "aisaa",
  "fir",
  "phir",
  "dobara",
  "wapas",

  // ── Hindi / Urdu — Question Words ──────────────────────────────────────────
  "kya",
  "kaun",
  "kaunsa",
  "kaunsi",
  "kaunse",
  "kitna",
  "kitni",
  "kitne",
  "kaisa",
  "kaisi",
  "kaise",
  "kab",
  "kahan",
  "kahin",
  "kyun",
  "kyon",
  "kisko",
  "kiske",
  "kiski",
  "kisi",
  "kisne",

  // ── Hindi / Urdu — Common Adverbs & Time Words ─────────────────────────────
  "ab",
  "abhi",
  "aaj",
  "kal",
  "parso",
  "pehle",
  "baad",
  "jaldi",
  "dhire",
  "dhire dhire",
  "kabhi",
  "kabhi kabhi",
  "hamesha",
  "aksar",
  "shayad",
  "zaroor",
  "bilkul",
  "thoda",
  "bahut",
  "zyada",
  "kam",
  "seedha",
  "sirf",
  "keval",
  "bhi",
  "hi",
  "toh",
  "woh",
  "sach",
  "theek",
  "sahi",
  "galat",
  "achha",
  "bura",
  "naya",
  "purana",
  "bada",
  "chota",
  "lamba",
  "chota",
  "upar",
  "neeche",
  "ander",
  "bahar",

  // ── Hindi / Urdu — Greetings & Filler ──────────────────────────────────────
  "haan",
  "han",
  "ji",
  "ji haan",
  "ji nahi",
  "theek hai",
  "thik hai",
  "shukriya",
  "dhanyavad",
  "namaste",
  "namaskar",
  "adaab",
  "salaam",
  "bhai",
  "behen",
  "didi",
  "bhaiya",
  "sahib",
  "madam",
  "accha",
  "achha",
  "acha",
  "arre",
  "dekho",
  "suno",
  "bolo",

  // ── Malayalam (Roman Script) — Pronouns & Demonstratives ───────────────────
  "njaan",
  "njan",
  "enikku",
  "ente",
  "ennude",
  "nammal",
  "namukku",
  "nammude",
  "ningal",
  "ningalku",
  "ningalude",
  "nee",
  "ninakku",
  "ninte",
  "avan",
  "avanu",
  "avante",
  "avanode",
  "aval",
  "avalku",
  "avalude",
  "avar",
  "avarku",
  "avarude",
  "athu",
  "atu",
  "ithu",
  "itu",
  "avar",
  "ivan",
  "ival",
  "ithil",
  "athil",
  "ivide",
  "avide",
  "evide",
  "ithinte",
  "athinte",

  // ── Malayalam — Verbs & Auxiliaries ────────────────────────────────────────
  "aanu",
  "aayirunnu",
  "aakum",
  "ayyi",
  "ayi",
  "aayitt",
  "aayi",
  "undu",
  "untu",
  "illa",
  "ille",
  "illayirunnu",
  "cheyyuka",
  "cheyyu",
  "cheythu",
  "cheythi",
  "cheyyan",
  "cheyyunnu",
  "varuka",
  "varunnu",
  "vannu",
  "varaan",
  "pokuka",
  "pokunnu",
  "poyi",
  "poan",
  "kodukkuka",
  "tharuka",
  "tharu",
  "tharan",
  "edukuka",
  "edukkuka",
  "eduthu",
  "nokkuka",
  "parayan",
  "parayuka",
  "parayunnu",
  "paranju",
  "kelkkuka",
  "kelkkunnu",
  "ketthu",
  "ariyuka",
  "ariyunnu",
  "ariyilla",
  "manassilakuka",
  "manassilayi",
  "manassilakunnu",
  "chodyikuka",
  "chodyicchu",
  "kanikuka",
  "kanikkunnu",
  "kaanuka",
  "kaanikkunnu",
  "thudanguka",
  "thudangi",
  "nilkuka",
  "nirtuka",
  "kazhiyuka",
  "kazhiyum",
  "kazhinju",
  "venam",
  "venda",
  "aavum",
  "aavathe",
  "pattum",
  "pattilla",
  "saadhikum",

  // ── Malayalam — Postpositions & Particles ───────────────────────────────────
  "ude",
  "kku",
  "il",
  "nte",
  "al",
  "aal",
  "kkay",
  "kayi",
  "nte",
  "nde",
  "ode",
  "um",
  "um",
  "aan",
  "aanu",
  "okke",
  "ellam",
  "mathram",
  "maathram",
  "koodi",
  "athre",
  "alle",
  "annu",
  "aanu",
  "anu",
  "enn",
  "ennu",
  "ennal",
  "engil",
  "appol",
  "athukond",
  "athukonte",
  "kondu",
  "kond",

  // ── Malayalam — Conjunctions & Discourse ───────────────────────────────────
  "um",
  "athava",
  "athaval",
  "pinne",
  "pakshe",
  "ennal",
  "engil",
  "ennalum",
  "enkilum",
  "karanam",
  "kondu",
  "athukond",
  "cheythitt",
  "kazhinju",
  "munpe",
  "shesham",
  "ennittum",
  "athu pole",
  "athupole",

  // ── Malayalam — Question Words ──────────────────────────────────────────────
  "enthu",
  "entha",
  "enthanu",
  "enthaanu",
  "evan",
  "evide",
  "eppo",
  "epozhu",
  "etra",
  "ethra",
  "engane",
  "evidunnu",
  "evanuttu",
  "aara",
  "aanu",
  "aavanu",

  // ── Malayalam — Common Adverbs & Particles ──────────────────────────────────
  "ipo",
  "ippo",
  "appol",
  "athu",
  "itu",
  "vere",
  "koodi",
  "kude",
  "mathram",
  "maathram",
  "sheri",
  "ille",
  "venam",
  "venda",
  "nannay",
  "nannayi",
  "padam",
  "sheriyanu",
  "athe",
  "aathe",
  "pinne",
  "munpe",
  "ippol",
  "appozhum",
  "eppozhum",
  "haa",
  "ee",
  "aa",
  "oru",
  "ath",
  "eth",
  "enth",
  "nokku",
  "pattu",
  "pol",
  "pole",
  "polum",
  "ennum",

  // ── Malayalam — Greetings & Fillers ─────────────────────────────────────────
  "namaskaram",
  "salam",
  "vanakkam",
  "nandri",
  "nanni",
  "njan",
  "cheeru",
  "ayyo",
  "acha",
  "enda",
  "mol",
  "mon",
  "chechi",
  "chettan",
  "saare",
  "teacher",
  "aniyathi",
  "aniyattiyan",

  // ── Tamil (Roman Script) — Pronouns & Demonstratives ──────────────────────
  "naan",
  "enakku",
  "ennai",
  "en",
  "yenakku",
  "naam",
  "namakku",
  "namai",
  "namma",
  "neenga",
  "neengalukku",
  "ungalukku",
  "ungal",
  "unakku",
  "unnai",
  "un",
  "avan",
  "avanukku",
  "avanai",
  "avane",
  "avana",
  "aval",
  "avalukku",
  "avalai",
  "avanga",
  "avargal",
  "avargalukku",
  "ithu",
  "idhu",
  "ithukku",
  "idhukku",
  "ithை",
  "ingey",
  "inge",
  "athu",
  "adhu",
  "athukku",
  "adhukku",
  "ange",
  "angey",
  "ivanga",
  "avanga",
  "ivaru",
  "avaru",

  // ── Tamil — Verbs & Auxiliaries ────────────────────────────────────────────
  "irukku",
  "irukken",
  "irukkeenga",
  "irundhu",
  "iruppen",
  "illa",
  "illai",
  "illen",
  "iллை",
  "aachu",
  "aagiduchu",
  "aagum",
  "aagiviatum",
  "pannuven",
  "pannuvom",
  "panrom",
  "panni",
  "panren",
  "pannitten",
  "pannitu",
  "pannanum",
  "pannakoodathu",
  "varuven",
  "varuom",
  "vaarunga",
  "vanthen",
  "vanthu",
  "pooven",
  "pooituven",
  "ponen",
  "poiduven",
  "poitu",
  "kuduppen",
  "kudunga",
  "kuduthen",
  "kudu",
  "tharuven",
  "tharuvom",
  "eduppen",
  "edunga",
  "eduththen",
  "edu",
  "solluven",
  "sollunga",
  "sollen",
  "sollu",
  "sonnen",
  "kekkuven",
  "kekkureenga",
  "ketten",
  "kelunga",
  "theriyum",
  "theriyathu",
  "therinja",
  "therijuchu",
  "puriyum",
  "puriyathu",
  "purinjuchu",
  "kelu",
  "paaru",
  "paarunga",
  "solu",
  "solunga",
  "vaa",
  "vaanga",
  "po",
  "ponga",
  "vaendam",
  "vaendum",
  "vaenum",
  "vaeno",
  "mudiyum",
  "mudiyathu",
  "mudinjuchu",

  // ── Tamil — Postpositions & Particles ──────────────────────────────────────
  "ukku",
  "kku",
  "al",
  "il",
  "odu",
  "oodu",
  "vitu",
  "vittu",
  "la",
  "le",
  "ley",
  "ku",
  "ai",
  "ei",
  "um",
  "aam",
  "thaan",
  "dan",
  "ye",
  "ngey",
  "ngey",
  "ellam",
  "konjam",
  "romba",
  "oru",
  "vera",
  "kita",
  "kitta",
  "pakkam",
  "paakam",

  // ── Tamil — Conjunctions & Discourse ───────────────────────────────────────
  "um",
  "mattum",
  "illana",
  "aana",
  "aanaa",
  "aavadhu",
  "adhavadhu",
  "yaen",
  "yen",
  "aandhale",
  "andhaale",
  "appadiye",
  "apparam",
  "pinbu",
  "munnadi",
  "mela",
  "keela",
  "adhunala",
  "andha",
  "inda",
  "appo",
  "ippo",

  // ── Tamil — Question Words ──────────────────────────────────────────────────
  "enna",
  "yenna",
  "yaar",
  "yange",
  "yeppo",
  "yenga",
  "yethana",
  "yeppadi",
  "eppadii",
  "enga",
  "eppo",
  "evan",
  "eval",
  "evanga",
  "ethu",
  "evvolo",
  "evvalavu",

  // ── Tamil — Common Adverbs & Particles ─────────────────────────────────────
  "ippo",
  "appo",
  "konjam",
  "romba",
  "oru",
  "mattum",
  "matum",
  "thaan",
  "dhan",
  "vera",
  "vegam",
  "mudhal",
  "varaikkum",
  "sari",
  "saridhan",
  "illa",
  "illai",
  "aa",
  "da",
  "di",
  "nga",
  "ma",
  "po",
  "dei",
  "machan",
  "pa",
  "ley",

  // ── Tamil — Greetings & Fillers ─────────────────────────────────────────────
  "vanakkam",
  "nandri",
  "nandrigal",
  "ayyo",
  "aiyyo",
  "adei",
  "enna koduma",
  "super",
  "nalla",
  "nalladhan",
  "anna",
  "akka",
  "thambi",
  "thangachi",
  "appa",
  "amma",
  "saar",
  "madam",
  "sir",

  // ── Telugu (Roman Script) — Pronouns & Demonstratives ─────────────────────
  "nenu",
  "naaku",
  "nanna",
  "nenu",
  "nannu",
  "memu",
  "maaku",
  "mammalani",
  "meeru",
  "meeraku",
  "meeru",
  "nuvvu",
  "nuvvaku",
  "ninnu",
  "nee",
  "atanu",
  "atanaki",
  "atanini",
  "atani",
  "aame",
  "aameaki",
  "aameani",
  "aaame",
  "vaallau",
  "vaariki",
  "vaallani",
  "idi",
  "idhi",
  "ikadi",
  "idhi",
  "ikkade",
  "adi",
  "adhi",
  "akadi",
  "adhi",
  "akkade",
  "ivaru",
  "avaru",
  "ivi",
  "avi",

  // ── Telugu — Verbs & Auxiliaries ────────────────────────────────────────────
  "undi",
  "unaanu",
  "unnaaru",
  "ledu",
  "ledhu",
  "lenidhi",
  "aindi",
  "ayindi",
  "autundi",
  "avutundi",
  "avutaanu",
  "avutaamu",
  "chesaanu",
  "chesaamu",
  "cheyyi",
  "cheyyandi",
  "chestunnaanu",
  "vastunnaanu",
  "vastunnaamu",
  "vachchaanu",
  "raa",
  "randi",
  "vellaanu",
  "vellaamu",
  "vellandi",
  "po",
  "pommandi",
  "istanu",
  "istaamu",
  "ichhaanu",
  "ivvandi",
  "tiskuntanu",
  "tisukuntanu",
  "teesaanu",
  "teesukonnanu",
  "cheppanu",
  "cheppamu",
  "cheppandi",
  "cheptunnaanu",
  "vinnaanu",
  "vinnaamu",
  "vinu",
  "vinandi",
  "teliyunu",
  "telidhu",
  "telisindi",
  "telustundi",
  "arthamavutundi",
  "arthamayindi",
  "adugutanu",
  "adugutamu",
  "adugandi",
  "chudanu",
  "chudamu",
  "chudandi",
  "choosanu",
  "moda pettu",
  "aapu",
  "aapandi",
  "kaavali",
  "vaddhu",
  "avutundi",
  "avvadhu",
  "cheyyagalanu",
  "cheyyagalamu",
  "cheyyalenu",

  // ── Telugu — Postpositions & Particles ─────────────────────────────────────
  "ki",
  "ku",
  "lo",
  "lo",
  "tho",
  "nundi",
  "valla",
  "kosam",
  "gurinchi",
  "pai",
  "kinda",
  "mundu",
  "taruvata",
  "lona",
  "kuda",
  "kooda",
  "matrame",
  "maatrame",
  "okka",
  "anni",
  "evi",
  "emaina",
  "evaina",
  "ela",
  "ala",
  "ilanti",
  "alanti",
  "ikkade",
  "akkade",

  // ── Telugu — Conjunctions & Discourse ──────────────────────────────────────
  "mariyu",
  "mariu",
  "leда",
  "leda",
  "kaani",
  "kaanee",
  "anduvalla",
  "kaabatti",
  "ayite",
  "ayitene",
  "aite",
  "ante",
  "antene",
  "taruvata",
  "mundhu",
  "kabbatti",
  "kani",
  "kunda",
  "kanakaala",
  "ilaa",
  "alaa",
  "appudu",
  "ippudu",

  // ── Telugu — Question Words ─────────────────────────────────────────────────
  "emiti",
  "emithi",
  "evaru",
  "ekkade",
  "eppudu",
  "enduku",
  "ela",
  "entha",
  "evadi",
  "evari",
  "evarite",
  "enti",
  "enthi",
  "emi",
  "emanna",
  "elaa",
  "evvade",

  // ── Telugu — Common Adverbs & Particles ─────────────────────────────────────
  "ippudu",
  "appudu",
  "inkaa",
  "inka",
  "chala",
  "chaala",
  "konjam",
  "okka",
  "anni",
  "aame",
  "ledhu",
  "avunu",
  "avunaa",
  "kadu",
  "sarE",
  "sare",
  "sariga",
  "tappaka",
  "veru",
  "veeru",
  "malli",
  "meeru",
  "meeru",
  "nijam",
  "nijame",
  "kadha",
  "kadaa",
  "aa",
  "ee",
  "oo",
  "emi",
  "ra",
  "raa",
  "ga",
  "le",
  "gaa",

  // ── Telugu — Greetings & Fillers ────────────────────────────────────────────
  "namaskaram",
  "dhanyavaadaalu",
  "dhanyavaadamulu",
  "ayyo",
  "arey",
  "baagundi",
  "baagaa",
  "manchidi",
  "manchigaa",
  "anna",
  "akka",
  "thammudu",
  "chelli",
  "amma",
  "naanna",
  "sir",
  "madam",
  "gaaru",

  // ── Kannada (Roman Script) — Basic ──────────────────────────────────────────
  "naanu",
  "nange",
  "nanage",
  "nanna",
  "naavu",
  "nammage",
  "namma",
  "neevu",
  "nimage",
  "nimma",
  "niin",
  "ninage",
  "ninna",
  "avanu",
  "avanige",
  "avana",
  "avalu",
  "avalige",
  "avala",
  "avaru",
  "avarige",
  "avara",
  "idu",
  "idhu",
  "illi",
  "adu",
  "adhu",
  "alli",
  "ide",
  "illa",
  "aagide",
  "aagilla",
  "aaguttade",
  "maadi",
  "maadutt",
  "maadbeku",
  "maadabeka",
  "barutt",
  "banni",
  "hoguttene",
  "hogbeku",
  "heli",
  "kelisikoli",
  "nodibidi",
  "thumba",
  "swalpa",
  "yaake",
  "yavaga",
  "elli",
  "hege",
  "yaaru",
  "yenu",
  "estu",
  "avaga",
  "ivaga",
  "innu",
  "kooda",
  "mattu",
  "athava",
  "aadare",
  "aadru",
  "aagbeku",
  "agla",
  "mundhe",
  "hinde",
  "sari",
  "illa",
  "howdu",
  "houdhu",
  "namskaara",
  "dhanyavaadagalu",

  // ── Marathi (Roman Script) — Basic ──────────────────────────────────────────
  "mi",
  "mala",
  "mazha",
  "majha",
  "amhi",
  "aamhala",
  "aamcha",
  "tu",
  "tula",
  "tuza",
  "tuzha",
  "tumhi",
  "tumhala",
  "tumcha",
  "to",
  "tyla",
  "tyala",
  "tyancha",
  "tiche",
  "te",
  "tyanna",
  "ha",
  "hi",
  "hya",
  "ithe",
  "tithe",
  "ithun",
  "ahe",
  "ahes",
  "naahi",
  "nahi",
  "hotam",
  "hote",
  "asel",
  "kar",
  "karto",
  "karti",
  "kele",
  "kela",
  "karayla",
  "karawa",
  "ya",
  "yeto",
  "yeti",
  "aala",
  "aali",
  "aale",
  "jaato",
  "jaati",
  "gele",
  "kasa",
  "kashi",
  "kuthe",
  "keva",
  "konti",
  "koni",
  "kititi",
  "kaay",
  "kay",
  "kaa",
  "aani",
  "va",
  "pan",
  "mhanun",
  "jevha",
  "tevha",
  "tar",
  "jarr",
  "ata",
  "mhanaje",
  "mhanje",
  "khup",
  "thoda",
  "sagala",
  "sarv",
  "ekach",
  "fakt",
  "hoy",
  "nako",
  "pahije",
  "shakto",
  "shakti",
  "shaktat",
  "namaskar",
  "dhanyavaad",
  "shukriya",
]);

function computeRelevanceScore(text: string): { score: number; detail: string } {
  // Normalise: lower-case, strip punctuation, split on whitespace
  const words = text
    .toLowerCase()
    .replace(/[^\w\s]/g, ' ')
    .split(/\s+/)
    .filter(Boolean);

  if (words.length === 0) {
    return { score: 0, detail: 'empty_input' };
  }

  let matched = 0;
  let agricultureWordCount = 0;

  for (const word of words) {
    if (STOP_WORDS.has(word)) continue;
    if (AGRICULTURE_KEYWORDS.has(word)) {
      matched++;
      agricultureWordCount++;
    }
    // Also check two-word phrases (bigrams) for composite terms like
    // "drip irrigation", "pigeon pea", "neem oil"
    const bigram = words
      .slice(words.indexOf(word), words.indexOf(word) + 2)
      .join(' ');
    if (bigram && bigram !== word && AGRICULTURE_KEYWORDS.has(bigram)) {
      matched++;
    }
  }

  const relevanceRatio = agricultureWordCount / words.length;

  // Scoring formula:
  //   min(1, agricultureWordCount * 0.15)  — rewards keyword density
  //   + min(0.3, relevanceRatio * 0.8)      — bonus for proportion of agri terms
  const score = Math.min(
    1,
    agricultureWordCount * 0.15 + Math.min(0.3, relevanceRatio * 0.8),
  );

  const detail =
    agricultureWordCount === 0
      ? 'no_agriculture_keywords'
      : `matched_${Math.min(agricultureWordCount, 20)}+_keywords`;

  return { score, detail };
}

// ─── Spam Detection ───────────────────────────────────────────────────────────

/** Regex patterns that strongly suggest spam or non-genuine content */
const SPAM_PATTERNS: Array<{ pattern: RegExp; label: string }> = [
  // Promotional / advertising
  { pattern: /\b(buy|sell|order|shop|discount|offer|free|gift|prize|winner|congratulations|winner|click here|register now|limited time)\b/gi, label: 'promotional' },
  // Repeated characters (e.g. "aaaaa" or "!!!!!!")
  { pattern: /(.)\1{5,}/g, label: 'repeated_chars' },
  // All caps or aggressive shouting (only flags if > 50% of words are caps)
  { pattern: /\b[A-Z]{5,}\b/g, label: 'excessive_caps' },
  // URLs
  { pattern: /https?:\/\/|www\./gi, label: 'url_present' },
  // Phone numbers / contact info in question body
  { pattern: /\b\d{10,}\b|\b\d[-.\s]?\d{3}[-.\s]?\d{3}[-.\s]?\d{4}\b/g, label: 'phone_number' },
  // Email addresses
  { pattern: /\b[\w.-]+@[\w.-]+\.\w{2,}\b/gi, label: 'email_address' },
  // Personal info solicitation
  { pattern: /\b(send|screenshot|whatsapp|telegram|instagram|facebook)\s+(me|my|to)\b/gi, label: 'social_solicitation' },
];

interface SpamCheckResult {
  pass: boolean;
  reasonKey: string | null;
  detail: string;
}

function checkSpam(text: string): SpamCheckResult {
  if (!text || text.trim().length === 0) {
    return { pass: true, reasonKey: null, detail: 'empty' };
  }

  for (const { pattern, label } of SPAM_PATTERNS) {
    // Reset regex lastIndex before each test
    pattern.lastIndex = 0;
    if (pattern.test(text)) {
      return { pass: false, reasonKey: `onDeviceAI.spam.${label}`, detail: label };
    }
  }

  // Check for very short, generic questions that are likely low-effort
  const words = text.trim().split(/\s+/);
  if (words.length < 3) {
    return { pass: false, reasonKey: 'onDeviceAI.spam.tooShort', detail: 'too_short' };
  }

  return { pass: true, reasonKey: null, detail: 'clean' };
}

// ─── Duplicate Detection ───────────────────────────────────────────────────────

/**
 * Compute Levenshtein (edit-distance) similarity ratio between two strings.
 * Returns a value in [0, 1] where 1 means identical.
 */
function levenshteinSimilarity(a: string, b: string): number {
  if (!a || !b) return 0;
  const s1 = a.toLowerCase().trim();
  const s2 = b.toLowerCase().trim();
  if (s1 === s2) return 1;

  const m = s1.length;
  const n = s2.length;
  if (m === 0 || n === 0) return 0;

  // Allocate a single row instead of full matrix to halve memory usage
  let prev = Array.from({ length: n + 1 }, (_, j) => j);
  let curr = new Array(n + 1).fill(0);

  for (let i = 1; i <= m; i++) {
    curr[0] = i;
    for (let j = 1; j <= n; j++) {
      const cost = s1[i - 1] === s2[j - 1] ? 0 : 1;
      curr[j] = Math.min(
        prev[j] + 1,     // deletion
        curr[j - 1] + 1, // insertion
        prev[j - 1] + cost, // substitution
      );
    }
    [prev, curr] = [curr, prev]; // swap without allocation
  }

  const maxLen = Math.max(m, n);
  return maxLen === 0 ? 0 : 1 - prev[n] / maxLen;
}

/**
 * Normalise text for exact-match comparison:
 * - lower-case, strip punctuation, collapse whitespace
 */
function normaliseForExact(text: string): string {
  return text.toLowerCase().replace(/[^\w\s]/g, ' ').replace(/\s+/g, ' ').trim();
}

interface DuplicateCheckResult {
  pass: boolean;
  duplicateQuestionId?: string;
  similarityScore?: number;
  reasonKey: string | null;
  detail: string;
}

async function checkDuplicate(
  text: string,
  _ownId?: string, // id of the question being edited — excluded from cache
): Promise<DuplicateCheckResult> {
  const normalised = normaliseForExact(text);

  if (!normalised || normalised.length < 10) {
    // Too short to reasonably compare
    return { pass: true, reasonKey: null, detail: 'too_short_for_comparison' };
  }

  // ── Exact match first ───────────────────────────────────────────────────────
  let cached: CachedQuestion[] = [];
  try {
    const raw = await AsyncStorage.getItem(DUPLICATE_CACHE_KEY);
    if (raw) cached = JSON.parse(raw) as CachedQuestion[];
  } catch {
    cached = [];
  }

  const now = Date.now();
  const validCache = cached.filter(
    (q) => now - new Date(q.cachedAt).getTime() < DUPLICATE_CACHE_TTL_MS,
  );

  // ── Step 1: exact (normalised) match ───────────────────────────────────────
  for (const entry of validCache) {
    if (normaliseForExact(entry.text) === normalised) {
      return {
        pass: false,
        duplicateQuestionId: entry.id,
        similarityScore: 1,
        reasonKey: 'onDeviceAI.duplicate.exact',
        detail: 'exact_match',
      };
    }
  }

  // ── Step 2: semantic similarity (Levenshtein ratio ≥ threshold) ────────────
  //    Use a "best score so far" loop to avoid O(n²) blow-up on large caches.
  const threshold = SIMILARITY_THRESHOLD;
  let bestScore = 0;
  let bestId: string | undefined;
  const maxComparisons = Math.min(validCache.length, 30); // cap at 30 to bound CPU

  for (let i = 0; i < maxComparisons; i++) {
    // Levenshtein is O(mn) per comparison; for short-to-medium strings
    // (≤ 300 chars) this is fast enough even for 30 comparisons.
    const score = levenshteinSimilarity(text, validCache[i].text);
    if (score > bestScore) {
      bestScore = score;
      bestId = validCache[i].id;
    }
    if (bestScore >= threshold) break; // early exit — no need to check more
  }

  if (bestScore >= threshold && bestId) {
    return {
      pass: false,
      duplicateQuestionId: bestId,
      similarityScore: bestScore,
      reasonKey: 'onDeviceAI.duplicate.semantic',
      detail: `semantic_similarity_${Math.round(bestScore * 100)}`,
    };
  }

  return { pass: true, reasonKey: null, detail: 'no_duplicate_found' };
}

/** Persist a newly submitted question to the duplicate cache */
export async function cacheQuestionForDuplicateDetection(
  id: string,
  text: string,
): Promise<void> {
  try {
    let cached: CachedQuestion[] = [];
    const raw = await AsyncStorage.getItem(DUPLICATE_CACHE_KEY);
    if (raw) cached = JSON.parse(raw) as CachedQuestion[];

    // Evict oldest entries once the cap is hit
    if (cached.length >= DUPLICATE_CACHE_MAX_ENTRIES) {
      cached.sort((a, b) => new Date(a.cachedAt).getTime() - new Date(b.cachedAt).getTime());
      cached = cached.slice(DUPLICATE_CACHE_MAX_ENTRIES * 0.3 | 0); // keep newest 70%
    }

    cached.push({ id, text, cachedAt: new Date().toISOString() });
    await AsyncStorage.setItem(DUPLICATE_CACHE_KEY, JSON.stringify(cached));
  } catch {
    // AsyncStorage failure is non-fatal for this feature
  }
}

// ─── Public Pipeline ───────────────────────────────────────────────────────────

export interface ValidationInput {
  /** The question text as typed / transcribed by the user */
  text: string;
  /** Optional question id — used to exclude own record during edit mode */
  ownId?: string;
}

/**
 * Run the full on-device validation pipeline.
 *
 * @param input  — { text, ownId? }
 * @returns AIValidationResult  — aggregated result with per-stage breakdown
 *
 * Behaviour:
 *   - Runs all three stages even if an early one fails, so UI can show all flags
 *   - `ran = false` when the environment lacks required APIs (e.g. pure web)
 *   - Never throws; always returns a valid AIValidationResult
 */
export async function runOnDeviceValidation(
  input: ValidationInput,
): Promise<AIValidationResult> {
  const { text, ownId } = input;

  // Catch non-fatal errors so a single stage crash doesn't block the pipeline
  let relevanceResult: StageResult = { pass: true, confidence: 1 };
  let duplicateResult: StageResult = { pass: true, confidence: 1 };
  let spamResult: StageResult = { pass: true, confidence: 1 };

  let relevanceReasonKey: string | null = null;
  let duplicateReasonKey: string | null = null;
  let spamReasonKey: string | null = null;

  let overallVerdict: AIValidationResult['verdict'] = 'pass';
  let overallMessage: string | null = null;
  let overallReasonKey: string | null = null;

  // ── 1. Spam detection (synchronous, always runs) ───────────────────────────
  try {
    const spam = checkSpam(text);
    spamResult = {
      pass: spam.pass,
      confidence: spam.pass ? 1 : 0.98,
      detail: spam.detail,
    };
    spamReasonKey = spam.reasonKey;
  } catch {
    spamResult = { pass: true, confidence: 0.5, detail: 'check_failed' };
  }

  // ── 2. Agriculture relevance (synchronous) ─────────────────────────────────
  try {
    // Skip relevance check when text is empty — let spam/checkSpam handle it
    if (!text.trim()) {
      relevanceResult = { pass: true, confidence: 1, detail: 'empty_input' };
    } else {
      const { score, detail } = computeRelevanceScore(text);
      const pass = score >= 0.15; // threshold tuned for short queries
      relevanceResult = {
        pass,
        confidence: score,
        detail,
      };
      if (!pass) relevanceReasonKey = 'onDeviceAI.relevance.low';
    }
  } catch {
    relevanceResult = { pass: true, confidence: 0.5, detail: 'check_failed' };
  }

  // ── 3. Duplicate detection (async — reads AsyncStorage) ────────────────────
  //    Skip on web (no AsyncStorage) to avoid blocking; duplicate check is
  //    always re-run server-side anyway.
  const canUseStorage =
    Platform.OS === 'ios' || Platform.OS === 'android';

  if (canUseStorage) {
    try {
      const dup = await checkDuplicate(text, ownId);
      duplicateResult = {
        pass: dup.pass,
        confidence: dup.similarityScore ?? 0,
        detail: dup.detail,
      };
      duplicateReasonKey = dup.reasonKey;
    } catch {
      duplicateResult = { pass: true, confidence: 0.5, detail: 'check_failed' };
    }
  }

  // ── Aggregate verdict ───────────────────────────────────────────────────────
  // Priority: spam > relevance > duplicate
  // spam FAIL        → fail  (hard block, cannot submit)
  // relevance FAIL   → fail  (hard block, cannot submit)
  // duplicate FAIL   → warn  (show banner, user can override)
  // all pass         → pass

  const spamFailed = !spamResult.pass;
  const duplicateFailed = !duplicateResult.pass;
  const relevanceFailed = !relevanceResult.pass;

  if (spamFailed) {
    overallVerdict = 'fail';
    overallReasonKey = spamReasonKey;
  } else if (relevanceFailed) {
    overallVerdict = 'fail';
    overallReasonKey = relevanceReasonKey;
  } else if (duplicateFailed) {
    overallVerdict = 'warn';
    overallReasonKey = duplicateReasonKey;
  } else {
    overallVerdict = 'pass';
  }

  return {
    verdict: overallVerdict,
    message: overallReasonKey, // caller resolves via i18n
    reasonKey: overallReasonKey,
    stages: {
      relevance: relevanceResult,
      duplicate: duplicateResult,
      spam: spamResult,
    },
    ran: true,
  };
}

/**
 * Lightweight synchronous pre-flight check suitable for debouncing on keystroke.
 * Returns the same verdict shape but skips AsyncStorage reads so it never await.
 *
 * Use this on `onChangeText` for a responsive "typing feedback" indicator.
 */
export function runOnDeviceValidationSync(input: Pick<ValidationInput, 'text'>): {
  relevanceScore: number;
  spamPass: boolean;
} {
  const { text } = input;
  const spam = checkSpam(text);
  const { score } = computeRelevanceScore(text);
  return { relevanceScore: score, spamPass: spam.pass };
}