export const CROPS = [
  "Adapathiyan",
  "Agathi",
  "Ailanthus or Matti",
  "Ajwain (Carom seeds)",
  "Allspice",
  "Almond",
  "Aloe vera",
  "Amaranth",
  "Amaranthus",
  "Amla",
  "Anthurium",
  "Apple",
  "Apricot",
  "Arecanut",
  "Arhar",
  "Arhar Dal (Red Gram)",
  "Aromatic Rice",
  "Arrow root",
  "Arum (Elephant Foot Yam)",
  "Arum Lobe",
  "Arum Stem",
  "Ash Gourd",
  "Ash gourd",
  "Ashwagandha",
  "Asoka",
  "Avocado",
  "Babool / Indian gum arabic tree",
  "Babool Tree",
  "Baby corn",
  "Babycorn",
  "Bajra/Pearl millet",
  "Bamboo",
  "Banana",
  "Banana Stem",
  "Barley",
  "Barnyard Millet",
  "Barnyard millet",
  "Beans",
  "Beet root",
  "Beetroot",
  "Bengal Gram",
  "Bengal Gram/Chickpea",
  "Ber",
  "Ber (Jujube)",
  "Berseem",
  "Betel Leaf",
  "Betel leaf",
  "Betel vine",
  "Bethua Leaves",
  "Beto Shak",
  "Bird of paradise",
  "Bitter Gourd",
  "Bitter gourd",
  "Black Cumin",
  "Black Gram",
  "Black Grapes",
  "Black Pepper",
  "Black gram",
  "Black pepper",
  "Blueberry",
  "Bottle Gourd",
  "Bottle gourd",
  "Brahmi",
  "Brinjal",
  "Brinjal (Eggplant)",
  "Brinjal / Eggplant",
  "Broad beans",
  "Broccoli",
  "Brocolli",
  "Brown Top Millet",
  "Buckwheat",
  "Butter / Mahua Tree",
  "Cabbage",
  "Camboge",
  "Capsicum",
  "Cardamom",
  "Carnation",
  "Carom",
  "Carrot",
  "Cashew",
  "Cassava (Tapioca)",
  "Cassia",
  "Castor",
  "Casuarina",
  "Cauliflower",
  "Celery",
  "Celery Seeds",
  "Ceylon Spinach",
  "Chadachi",
  "Char Magaz",
  "Chayote",
  "Chengazhinirkizhangu",
  "Chethikoduveli",
  "Chick pea",
  "Chickpea",
  "Chickpea, Bengal gram",
  "Chikoo",
  "Chilli",
  "Chilly",
  "China aster",
  "Chinese cabbage",
  "Chittadalotakam",
  "Chittaratha",
  "Chow Chow",
  "Chrysanthemum",
  "Cinnamon",
  "Citronella grass",
  "Citrus",
  "Clove",
  "Cloves",
  "Cluster bean",
  "Cocoa",
  "Coconut",
  "Coffee",
  "Coleus",
  "Colocacia",
  "Colocasia",
  "Congosignal grass",
  "Coriander",
  "Coriander (Cilantro)",
  "Coriander Leaves/Seeds",
  "Cotton",
  "Cowpea",
  "Crossandra",
  "Cucumber",
  "Cumin",
  "Cumin Seeds",
  "Curry leaves",
  "Custard Apple",
  "Custard apple",
  "Daincha",
  "Danthappala",
  "Darjeeling Orange",
  "Date",
  "Date Palm",
  "Date palm",
  "Davana",
  "Dill leaves",
  "Dillseed",
  "Dragon Fruit",
  "Drumstick",
  "Drumstick (Moringa)",
  "Elephant Apple",
  "Elephant Foot Yam",
  "Eucalyptus",
  "Fennel",
  "Fenugreek",
  "Fenugreek (Methi)",
  "Field pea",
  "Fig",
  "Finger Millet",
  "Finger millet",
  "Firecracker flower",
  "Fodder cowpea",
  "Fodder maize",
  "Fodder sorghum",
  "Foxtail Millet",
  "Foxtail millet",
  "French bean",
  "Gaillardia",
  "Galgal (Hill Lemon)",
  "Gamba grass",
  "Garlic",
  "Geranium",
  "Gerbera",
  "German Turnip",
  "Gherkins",
  "Ginger",
  "Gladiolus",
  "Gliricidia",
  "Gram",
  "Grape",
  "Grapes",
  "Greater yam",
  "Green Cardamom",
  "Green Chilli",
  "Green Gram",
  "Green Mango",
  "Green Papaya",
  "Green Peas",
  "Green gram",
  "Green gram, Golden gram",
  "Green pea",
  "Greeng gram",
  "Ground Nut",
  "Groundnut",
  "Guava",
  "Guinea grass",
  "Gymnema (Sugar destroyer)",
  "Hedge lucerne",
  "Heliconia",
  "Hogplum",
  "Holy basil",
  "Honey Plant",
  "Hops",
  "Horse Gram",
  "Horse gram",
  "Horsegram",
  "Hyacinth Bean",
  "Hyacinth Bean or Lablab Bean",
  "Hybrid napier",
  "Indian Beech / Pongam Tree",
  "Indian Beech Tree",
  "Indian Blackberry",
  "Indian Butter Tree / Mahua",
  "Indian Gooseberry",
  "Indian Gooseberry (Amla)",
  "Indian Jujube (Ber)",
  "Indian gooseberry",
  "Indian hogweed / Spiny amaranth",
  "Indian mustard",
  "Indian sarsaparilla (Mangani root)",
  "Indigo",
  "Irul",
  "Ivy Gourd",
  "Ivy gourd",
  "Jack",
  "Jack Fruit",
  "Jack fruit",
  "Jackfruit",
  "Jamun",
  "Jamun fruit",
  "Japanese Persimmon",
  "Jasmine",
  "Jeevakom",
  "Jicama",
  "Jute Leaves",
  "Kacholam",
  "Kagzi Lime",
  "Kalai Dal",
  "Kampakam",
  "Kanjiram",
  "Karinochi",
  "Karonda",
  "Kashi kanagile",
  "Kasthurimanjal",
  "Kattarvazha",
  "Kidney Bean",
  "Kidney bean",
  "Kidney bean/Rajama",
  "Kinnow (mandarin)",
  "Kiwifruit",
  "Knol-khol",
  "Kodo millet",
  "Kokum",
  "Koovalam",
  "Kurumthotti",
  "Kusuma",
  "Lady's Finger",
  "Large Cardamom",
  "Lemon",
  "Lemongrass",
  "Lentil",
  "Lesser yarm",
  "Lettuce",
  "Lime / Lemon",
  "Linseed",
  "Linseed, Flax",
  "Litchi",
  "Little Millet",
  "Little millet",
  "Long melon",
  "Long pepper",
  "Loquat",
  "Lucerne",
  "Mahagony",
  "Mahogany",
  "Maize",
  "Malabar Neem",
  "Mandarin",
  "Mandarin orange",
  "Mangium",
  "Mango",
  "Mango-ginger",
  "Mangosteen",
  "Marigold",
  "Mash",
  "Matar Dal (Split peas)",
  "Mentha",
  "Mesta",
  "Millet",
  "Moong",
  "Moong Dal",
  "Moth Bean",
  "Moth bean",
  "Mung",
  "Mung bean",
  "Mushroom",
  "Muskmelon",
  "Mustard",
  "Musur Dal",
  "Napier Grass",
  "Neela amari",
  "Neem",
  "Neem (ground type)",
  "Niger",
  "Nilappana",
  "Nutmeg",
  "Oat",
  "Oats",
  "Oilpalm",
  "Okra",
  "Okra (Lady\u2019s finger)",
  "Olive",
  "Onion",
  "Orange",
  "Orange (Sweet Orange / Mosambi)",
  "Orchids",
  "Paddy",
  "Palmarosa",
  "Palmarosa grass",
  "Palmyra palm",
  "Papaya",
  "Para grass",
  "Paradise Tree",
  "Passion fruit",
  "Patchouli",
  "Pathimugham",
  "Pea",
  "Peach",
  "Pear",
  "Pearl Millet",
  "Pearl millet",
  "Pecan Nut",
  "Physic Nut / Jatropha",
  "Pickling melon",
  "Pigeon Pea",
  "Pigeon pea",
  "Pigeon pea, Red gram",
  "Pineapple",
  "Plum",
  "Pointed Gourd",
  "Pomegranate",
  "Potato",
  "Proso millet",
  "Proso milllet",
  "Pumpkin",
  "Punna",
  "Quina",
  "Raddish",
  "Radish",
  "Ragi",
  "Ramboothan",
  "Ramphal",
  "Rapeseed and Mustard",
  "Raw Bengal Gram",
  "Red Chilli",
  "Red Gram/Pigeon Pea",
  "Red Sandalwood",
  "Red Sanders / Red Sandalwood",
  "Red gram",
  "Rice",
  "Ridge Gourd",
  "Ridge gourd",
  "Ripe Papaya",
  "Rose",
  "Rose (Greenhouse)",
  "Roselle / Red sorrel",
  "Rosemary",
  "Rosewood",
  "Round gourd",
  "Rubber",
  "Ryegrass",
  "Safed musli",
  "Safflower",
  "Sandal",
  "Sandalwood",
  "Sapodilla (Chiku)",
  "Sapota",
  "Sarpagandha (Indian snakeroot)",
  "Senji",
  "Sesame",
  "Sesame, Gingelly",
  "Setaria grass",
  "Shaftal",
  "Shah Marich",
  "Shevri",
  "Snake Gourd",
  "Snake gourd",
  "Sorghum",
  "Sorghum (Fodder)",
  "Sorghum (Rabi/Kharif)",
  "Soyabean",
  "Soybean",
  "Spinach",
  "Sponge gourd",
  "Squash",
  "Stevia",
  "Strawberry",
  "Stylo",
  "Subabul",
  "Sugarbeet",
  "Sugarcane",
  "Summer squash",
  "Sun hemp",
  "Sunflower",
  "Sweet Cherry",
  "Sweet Lemon",
  "Sweet Lime",
  "Sweet orange",
  "Sweet pepper",
  "Sweet potato",
  "Tamarind",
  "Tapioca",
  "Tea",
  "Teak",
  "Thembavu",
  "Thippali",
  "Thorny bamboo",
  "Thulasi",
  "Tobacco",
  "Tomato",
  "Tree Tomato",
  "Tuberose",
  "Tulsi (Holy basil)",
  "Turmeric",
  "Turnip",
  "Urd",
  "Vanilla",
  "Vegetable cowpea",
  "Venga",
  "Vetiver",
  "Vetiver (Khus grass)",
  "Walnut",
  "Wanga",
  "Water melon",
  "Watermelon",
  "West Indian Cherry",
  "Wheat",
  "White yam",
  "Wild Tamarind",
  "Wild date palm",
  "Wild indigo",
  "Wild jack or Aini",
  "Wood apple",
  "Yam",
] as const;
